### ISSUE TITLE
How to run test suite on build from source?

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#10]
When I build from source, share/testsuite doesn't exist, how can I run it to confirm my built version works properly?

**Comment by vfonov** [comment]
yes, that's a separate project right now. 
You will have to download and install https://github.com/BIC-MNI/bic-mni-models, https://github.com/BIC-MNI/BEaST_library and https://github.com/BIC-MNI/minc-toolkit-testsuite. 

P.S. that will work with minc-toolkit (not -v2)
