### ISSUE TITLE
CMake error

### ISSUE THREAD

**Issue by ekuama** [BIC-MNI/minc-toolkit-v2#100]
CMake Error at cmake-modules/BuildZLIB.cmake:99 (configure_file):
   configure_file Problem configuring file
 Call Stack (most recent call first):
   CMakeLists.txt:181 (build_zlib)

 CMake Error at /usr/share/cmake-3.10/Modules/ExternalProject.cmake:2778 (configure_file):
   configure_file Problem configuring file
 Call Stack (most recent call first):
   /usr/share/cmake-3.10/Modules/ExternalProject.cmake:3032 (_ep_add_configure_command)
   cmake-modules/BuildHDF5.cmake:71 (ExternalProject_Add)
   CMakeLists.txt:210 (build_hdf5)

 CMake Error at /usr/share/cmake-3.10/Modules/ExternalProject.cmake:2778 (configure_file):
   configure_file Problem configuring file
 Call Stack (most recent call first):
   /usr/share/cmake-3.10/Modules/ExternalProject.cmake:3032 (_ep_add_configure_command)
   cmake-modules/BuildNIFTI.cmake:68 (ExternalProject_Add)
   CMakeLists.txt:220 (build_nifti)

**Comment by gdevenyi** [comment]
Hi,

Please provide complete information of your system as well as the *complete* output of all commands provided.

**Comment by gdevenyi** [comment]
Also, please consider if you really need to build from source, and instead install from binaries available here: https://bic-mni.github.io/
