### ISSUE TITLE
Bad variable name for sh /opt/minc/1.9.17/minc-toolkit-config.sh

### ISSUE THREAD

**Issue by ekuama** [BIC-MNI/minc-toolkit-v2#101]
I am using a Windows 10 Pro and I installed Ubuntu 18.04 using the Windows Subsystem for Linux (WSL).  I followed the instructions on the https://bic-mni.github.io/#on-debianubuntu to install the minc-toolkit. To use it per instructions I have to  source the environment in /opt/minc/1.9.17/minc-toolkit-config.sh for bash

$ sh /opt/minc/1.9.17/minc-toolkit-config.sh
/opt/minc/1.9.17/minc-toolkit-config.sh: 4: export: Files/WindowsApps/CanonicalGroupLimited.UbuntuonWindows_1804.2019.521.0_x64__79rhkp1fndgsc:/mnt/c/Program: bad variable name

**Comment by gdevenyi** [comment]
Your command says 'sh' not 'source' as per the instructions.

**Comment by vfonov** [comment]
well, it will not work with path that contains spaces.

**Comment by ekuama** [comment]
Thank you. With 'source', it works

**Comment by ekuama** [comment]
Now I face a new error
freeglut (no_program_name): failed to open display ''

when I type in this 

$ Display /mnt/c/Users/user/Desktop/RESECT/MINC/Case1/US/Case1-US-after.mnc
or 
$ register /mnt/c/Users/user/Desktop/RESECT/MINC/Case1/US/Case1-US-after.mnc /mnt/c/Users/user/Desktop/RESECT/MINC/Case1/US/Case1-US-before.mnc /mnt/c/Users/user/Desktop/RESECT/MINC/Case1/landmarks/Case1-beforeUS-afterUS.tag

**Comment by vfonov** [comment]
You need X server

**Comment by ekuama** [comment]
> You need X server

For windows or for ubuntu
