### ISSUE TITLE
minc-toolkit-config.sh accidentally adds current directory to empty profile variables

### ISSUE THREAD

**Issue by hazedine** [BIC-MNI/minc-toolkit-v2#102]
There is a weird slowness when using the minc tools on a sshfs mounted directory.

```shell
$ cd tmp; time firefox
real	0m0,587s
user	0m0,097s
sys	0m0,016s

$ cd /mnt/sshfs/some_directory; time firefox
real	0m18,212s
user	0m0,111s
sys	0m0,020s
```

 It turns out the issue is in the configurations settings, more specifically:

```shell
export LD_LIBRARY_PATH=${MINC_TOOLKIT}/lib:${MINC_TOOLKIT}/lib/InsightToolkit:${LD_LIBRARY_PATH}
echo ${LD_LIBRARY_PATH}
/opt/minc/1.9.16/lib:/opt/minc/1.9.16/lib/InsightToolkit:
```
The semi column at the end add the current working directory to the lookup paths.

To fix it:
```shell
export LD_LIBRARY_PATH=${MINC_TOOLKIT}/lib:${MINC_TOOLKIT}/lib/InsightToolkit${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
```

The same issue for PATH, PERL5LIB and MANPATH.

**Comment by gdevenyi** [comment]
Quoting from the bash manual the source of the problem:

> PATH
> The search path for commands. It is a colon-separated list of directories in which the shell looks for commands (see COMMAND EXECUTION below). A zero-length (null) directory name in the value of PATH indicates the current directory. A null directory name may appear as two adjacent colons, or as an initial or trailing colon. The default path is sys‐tem-dependent, and is set by the administrator who installs bash. A common value is ``/usr/gnu/bin:/usr/local/bin:/usr/ucb:/bin:/usr/bin''.

Need to fix https://github.com/BIC-MNI/minc-toolkit-v2/blob/master/minc-toolkit-config.unix.sh.cmake

Thanks for the report.

**Comment by vfonov** [comment]
technically, we don't need to setup LD_LIBRARY_PATH at all, since on MacOS it is very restrictive, all the binaries now should have properly set RPATHs to find the shared libraries.

**Comment by gdevenyi** [comment]
@vfonov indeed, I was thinking about that recently when I redid the ANTs build/install. Will  test commenting out the unneeded variables and see if RPATH is properly working on Linux.

**Comment by gdevenyi** [comment]
Fixed.
