### ISSUE TITLE
beast testing file is using old path which doesn't exist

### ISSUE THREAD

**Issue by sebastian-burlacu** [BIC-MNI/minc-toolkit-v2#103]
When running the latest build instructions, the BEaST/Testing/CMakeLists.txt TESTING_LIBRARY_URL is set to the mcgill link which doesn't exist. I had to manually update it to the github link, as noted here https://github.com/BIC-MNI/BEaST/issues/11

**Comment by gdevenyi** [comment]
Already reported and fixed in Beast:
https://github.com/BIC-MNI/BEaST/issues/11

Will be fixed in next minc-toolkit-v2 release.
