### ISSUE TITLE
ANTs on branch develop not being built with gzip support

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#11]
ANTs seem to missing gzip support on develop branch, causing it to fail if anything other than minc is use for output (because ANTs wants to create an .nii.gz file by default)

Also cannot open .nii.gz files as a result.

**Comment by vfonov** [comment]
I noticed, but can't find the source of the problem. ITK is built with ZLIB : https://github.com/BIC-MNI/minc-toolkit-v2/blob/develop/cmake-modules/BuildITKv4.cmake#L106

**Comment by rdvincent** [comment]
Some tools and libraries need to have HAVE_ZLIB=1 defined. I added it to CMakeLists.txt in minc-toolkit, but I noticed that was not carried over to minc-toolkit-v2.

**Comment by vfonov** [comment]
ITK is built as external project - it doesn't have HAVE_ZLIB switch from what I know.

**Comment by vfonov** [comment]
Ok, I have tracked this problem. It is caused by the conflict in nifti libraries between the one in ITK and another one in libminc. For now, I disabled niftilib inside of libminc unless it is explicitly enabled in configuration.
