### ISSUE TITLE
bestlinreg_s : argument "-lsq7", but not "-lsq6" or "-lsq9", turns all voxels into 0's 

### ISSUE THREAD

**Issue by rwickens** [BIC-MNI/minc-toolkit-v2#114]
Hi there, 

I'm using minc v. 1.9.17 on linux. When I run the bestlinreg_s script, passing in the argument "-lsq6" works well, but "-lsq7" turns all the voxels into 0s (after I apply the resulting xfms to my image). 
Interestingly, when I run the "-lsq7", I get the following output:  
![101063685_2637204726497979_3364162846899306496_n](https://user-images.githubusercontent.com/24905802/83713100-3c921a80-a5f5-11ea-818d-7e5382afe4a0.png)
The multiple "0.00 = T" weren't present when using "-lsq6" or "-lsq9"
Thanks a lot.

**Comment by gdevenyi** [comment]
Please share the complete commands and their outputs as text in the issuem

**Comment by vfonov** [comment]
it looks like optimization procedure found an "optimum" by mapping one image completely outside of another one. 
You can try bestlinreg with revised parameters: https://raw.githubusercontent.com/BIC-MNI/EZminc/ITK4/scripts/bestlinreg_claude.pl

**Comment by rwickens** [comment]
> Please share the complete commands and their outputs as text in the issuem
Yes, happily:
--------------------RWICKENS COMMAND:------------------------------------- 
source /opt/minc/1.9.17/minc-toolkit-config.sh
/opt/minc/1.9.17/bin/bestlinreg_s -clobber -lsq7 -nmi /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv.mnc /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_t1.mnc /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_autoreg.xfm /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_autoreg.mnc

-------------------RWICKENS OUTPUT-----------------------------------------

Transforming slices:................................................................................................................................................................................................................................................................Done
-+-------------------------[0]-------------------------
 | steps:          8 8 8
 | blur_fwhm:      16
 | simplex:        32
 | source:         /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_16_blur.mnc
 | target:         /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_16_blur.mnc
 | xfm:            /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_0.xfm
-+-----------------------------------------------------

mincblur -clobber -no_apodize -fwhm 16 /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_16
Blurring volume: ..............................................................
Making byte volume...
mincblur -clobber -no_apodize -fwhm 16 /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_t1.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_16
Blurring volume: ..............................................................
Making byte volume...
minctracc -clobber -lsq7 -step 8 8 8 -simplex 32 -tol 0.01 -est_translations -nmi /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_16_blur.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_16_blur.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_0.xfm
COG of v1: 5.614928 1.857713 -161.797623
COG of v2: 4.908897 20.815512 -52.983429
   [trans] = -0.706031 18.957798 108.814194
Only center & trans required, now returning from init_transformation
WARNING: source volume not UNSIGNED BYTE, will do conversion now.
WARNING: target volume not UNSIGNED BYTE, will do conversion now.
Initial objective function val = -0.04215776
Final objective function value = -0.13925168
-+-------------------------[1]-------------------------
 | steps:          4 4 4
 | blur_fwhm:      8
 | simplex:        16
 | source:         /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_8_blur.mnc
 | target:         /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_8_blur.mnc
 | xfm:            /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_1.xfm
-+-----------------------------------------------------

mincblur -clobber -no_apodize -fwhm 8 /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_8
Blurring volume: ..............................................................
Making byte volume...
mincblur -clobber -no_apodize -fwhm 8 /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_t1.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_8
Blurring volume: ..............................................................
Making byte volume...
minctracc -clobber -lsq7 -step 4 4 4 -simplex 16 -tol 0.004 -transformation /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_0.xfm -nmi /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_8_blur.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_8_blur.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_1.xfm
WARNING: source volume not UNSIGNED BYTE, will do conversion now.
WARNING: target volume not UNSIGNED BYTE, will do conversion now.
out :  0.0129=T  0.0006=T -0.2101=T   -0.1899=F -0.1899=F -0.1899=F    0.0000=T  0.0000=T  0.0000=T 
out : -0.0669=T -0.0792=T -0.1303=T   -0.1899=F -0.1899=F -0.1899=F    0.0000=T  0.0000=T  0.0000=T 
out : -0.0469=T -0.0592=T -0.1502=T   -0.0299=F -0.0299=F -0.0299=F    0.0000=T  0.0000=T  0.0000=T 
Initial objective function val = -0.02660915
Final objective function value = -0.23572497
-+-------------------------[2]-------------------------
 | steps:          4 4 4
 | blur_fwhm:      8
 | simplex:        16
 | source:         /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_8_blur.mnc
 | target:         /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_8_blur.mnc
 | xfm:            /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_2.xfm
-+-----------------------------------------------------

minctracc -clobber -lsq7 -step 4 4 4 -simplex 16 -tol 0.0001 -transformation /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_1.xfm -nmi /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_8_blur.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_8_blur.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_2.xfm
WARNING: source volume not UNSIGNED BYTE, will do conversion now.
WARNING: target volume not UNSIGNED BYTE, will do conversion now.
out :  0.0602=T  0.0831=T -0.2076=T   -0.2746=F -0.2746=F -0.2746=F    0.0000=T  0.0000=T  0.0000=T 
out :  0.1400=T  0.0034=T -0.2874=T   -0.2746=F -0.2746=F -0.2746=F    0.0000=T  0.0000=T  0.0000=T 
out :  0.1201=T  0.0233=T -0.2674=T   -0.1146=F -0.1146=F -0.1146=F    0.0000=T  0.0000=T  0.0000=T 
out :  0.1101=T  0.0333=T -0.2574=T   -0.0346=F -0.0346=F -0.0346=F    0.0000=T  0.0000=T  0.0000=T 
Initial objective function val = -0.23572947
Final objective function value = -0.25773442
-+-------------------------[3]-------------------------
 | steps:          4 4 4
 | blur_fwhm:      4
 | simplex:        8
 | source:         /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_4_blur.mnc
 | target:         /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_4_blur.mnc
 | xfm:            /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_3.xfm
-+-----------------------------------------------------

mincblur -clobber -no_apodize -fwhm 4 /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_4
Blurring volume: ..............................................................
Making byte volume...
mincblur -clobber -no_apodize -fwhm 4 /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_t1.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_4
Blurring volume: ..............................................................
Making byte volume...
minctracc -clobber -lsq7 -step 4 4 4 -simplex 8 -tol 0.0001 -transformation /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_2.xfm -nmi /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_4_blur.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_4_blur.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_3.xfm
WARNING: source volume not UNSIGNED BYTE, will do conversion now.
WARNING: target volume not UNSIGNED BYTE, will do conversion now.
out :  0.0603=T  0.0831=T -0.2076=T   -0.1146=F -0.1146=F -0.1146=F    0.0000=T  0.0000=T  0.0000=T 
out :  0.1002=T  0.1230=T -0.1677=T   -0.1146=F -0.1146=F -0.1146=F    0.0000=T  0.0000=T  0.0000=T 
out :  0.0902=T  0.1130=T -0.1777=T   -0.0346=F -0.0346=F -0.0346=F    0.0000=T  0.0000=T  0.0000=T 
Initial objective function val = -0.20486872
Final objective function value = -0.23765591
-+-------------------------[4]-------------------------
 | steps:          2 2 2
 | blur_fwhm:      2
 | simplex:        4
 | source:         /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_2_blur.mnc
 | target:         /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_2_blur.mnc
 | xfm:            /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_4.xfm
-+-----------------------------------------------------

mincblur -clobber -no_apodize -fwhm 2 /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_2
Blurring volume: ..............................................................
Making byte volume...
mincblur -clobber -no_apodize -fwhm 2 /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_t1.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_2
Blurring volume: ..............................................................
Making byte volume...
minctracc -clobber -lsq7 -step 2 2 2 -simplex 4 -tol 0.0005 -transformation /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_3.xfm -nmi /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_2_blur.mnc /tmp/bestlinreg_s-5YgobssE/t_FEOBV_PD_N50_01000104_t1_2_blur.mnc /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_4.xfm
WARNING: source volume not UNSIGNED BYTE, will do conversion now.
WARNING: target volume not UNSIGNED BYTE, will do conversion now.
out :  0.0593=T  0.0847=T -0.0717=T   -0.0347=F -0.0347=F -0.0347=F    0.0000=T  0.0000=T  0.0000=T 
out :  0.0394=T  0.1047=T -0.0916=T   -0.0347=F -0.0347=F -0.0347=F    0.0000=T  0.0000=T  0.0000=T 
Initial objective function val = -0.05800940
Final objective function value = -0.25724339
mv -f /tmp/bestlinreg_s-5YgobssE/s_XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_4.xfm /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_autoreg.xfm
mincresample -clobber -like /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_t1.mnc -transformation /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_autoreg.xfm /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv.mnc /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_autoreg.mnc
-+- creating /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_avg_suv_autoreg.mnc using /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_autoreg.xfm
1

------------------------RWICKENS COMMAND------------------------------

xfmconcat -clobber /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_autoreg.xfm /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_t1_tal.xfm /home/minc/Desktop/PROJECT/Subject1/FEOBV_PD_N50_01000104_nlfit_It.xfm /home/minc/Desktop/PROJECT/Subject1/XXXX01-FEOBV-HRRT1248-2017-8-16-15-50-9_EMMASK_4D_MC01_autoreg_toST.xfm

-----------------------RWICKENS OUTPUT----------------------------------------------

Outputting Volume: ............................................................


Transforming slices:.................................................................................................................................................................................................Done

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

There is no error outputted by MINC, but when I calculate the radioactivity in the mask region it comes out as 0; the PET file is almost entirely black; and there is a correlation of .001 between the file outputted when using "-lsq7" versus the one outputted by "-lsq6" argument.

**Comment by gdevenyi** [comment]
I am also partial to bestlinreg_g, https://raw.githubusercontent.com/BIC-MNI/EZminc/ITK4/scripts/bestlinreg_g its very similar to the claude one.

**Comment by gdevenyi** [comment]
Other things that are likely to help here are to provide brain masks to bestlinreg, to focus the registation to the region of interest.

**Comment by rwickens** [comment]
Thanks a lot, this was helpful!

**Comment by rwickens** [comment]
@vfonov, is the script with revised parameters that you posted = to the  "revised bestlinreg script" mentioned in [Dadar, M., Fonov, V.S., Collins, D.L., A comparison of publicly available linear MRI stereotaxic registration techniques, NeuroImage (2018)] ?

**Comment by vfonov** [comment]
yes, that's the one.
