### ISSUE TITLE
register tools segmentation fault all the time

### ISSUE THREAD

**Issue by w19787** [BIC-MNI/minc-toolkit-v2#115]
OS: ubuntu 18.04
minc-toolkit version: 1.9.17
The segmentation fault occur on following 2 cases:
1. just open register without open any file, and press quit button. after quit. the system report segment fault.
2. register 1.mnc 2.mnc landmark_tag. the application launch and you can see the file is loading, but it crash after 1s.
![image](https://user-images.githubusercontent.com/731496/83730098-2cbd1980-a67b-11ea-89a8-eea3b6a22311.png)

**Comment by gdevenyi** [comment]
Please describe how you obtained minc-toolkit-v2

**Comment by vfonov** [comment]
that's issue with recent Freeglut included in Ubuntu. For minc-toolkit binary package we use particular version of freeglut.

**Comment by w19787** [comment]
> Please describe how you obtained minc-toolkit-v2
i have tried the both way, including download the pre-built deb package or compile from source code. 

but got no luck.

**Comment by w19787** [comment]
> that's issue with recent Freeglut included in Ubuntu. For minc-toolkit binary package we use particular version of freeglut.

how can i solve the problem?

**Comment by vfonov** [comment]
build minc-toolkit and specify USE_SYSTEM_GLUT:BOOL=OFF in configuration.

**Comment by w19787** [comment]
> build minc-toolkit and specify USE_SYSTEM_GLUT:BOOL=OFF in configuration.

This is the build configuration i used. ALL SYSTEM config has been set to OFF. 
![image](https://user-images.githubusercontent.com/731496/83938305-ab45c280-a805-11ea-8adb-f0d30ff9c5af.png)

![image](https://user-images.githubusercontent.com/731496/83938299-99641f80-a805-11ea-9395-6cd4fd77ffa4.png)

**Comment by w19787** [comment]
> build minc-toolkit and specify USE_SYSTEM_GLUT:BOOL=OFF in configuration.

i am wondering it might be caused by my gpu card. currently i am using Nvidia p6000 card for computing and display. but no clue how to verify it.

**Comment by vfonov** [comment]
you can use glxinfo to see if your x11 supports opengl

**Comment by w19787** [comment]
> you can use glxinfo to see if your x11 supports opengl

it seems openGL is supported
![image](https://user-images.githubusercontent.com/731496/83946832-d4864300-a845-11ea-9388-884eec50b1c7.png)

**Comment by w19787** [comment]
> you can use glxinfo to see if your x11 supports opengl

![image](https://user-images.githubusercontent.com/731496/83947275-99394380-a848-11ea-9bb9-19f803f68675.png)

**Comment by w19787** [comment]
![image](https://user-images.githubusercontent.com/731496/83947520-16b18380-a84a-11ea-908c-fa9729f35645.png)

**Comment by vfonov** [comment]
better post the complete output of `glxinfo` , not the screenshot and no grep filter
also, check that `glxgears` works.

**Comment by gdevenyi** [comment]
For a counterpoint here, I'm running 18.04 with nvidia-440 on a 1080Ti that works fine with both the 18.04 debs and a local build of devel-1.9.18 with -DUSE_SYSTEM_GLUT:BOOL=OFF.

**Comment by w19787** [comment]
[glxinfo.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/4742194/glxinfo.txt)

**Comment by w19787** [comment]
> For a counterpoint here, I'm running 18.04 with nvidia-440 on a 1080Ti that works fine with both the 18.04 debs and a local build of devel-1.9.18 with `-DUSE_SYSTEM_GLUT:BOOL=OFF`.

[glxinfo.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/4742196/glxinfo.txt)

**Comment by vfonov** [comment]
well, one thing different from my system seem to be that you have two different screens running simultaneously maybe you can try running a single session  - see what happens.

**Comment by w19787** [comment]
> well, one thing different from my system seem to be that you have two different screens running simultaneously maybe you can try running a single session - see what happens.

i only have one monitor attach to the system. the following is output of "/usr/bin/nvidia-xconfig --query-gpu-info"
![image](https://user-images.githubusercontent.com/731496/84007319-cb5eb880-a9a2-11ea-95b5-707368fe5be2.png)

**Comment by vfonov** [comment]
is there another instance of x11 session running in background?

**Comment by w19787** [comment]
> is there another instance of x11 session running in background?

i use ps to check x11 background, it do have 2 session. but kill any one of them, the result still keep same.
![image](https://user-images.githubusercontent.com/731496/84148281-574f0e00-aa91-11ea-8b0d-08e88acbfaa0.png)

**Comment by vfonov** [comment]
ibus-x11 is not an x11 server, it's a program to enter special characters etc
https://wiki.archlinux.org/index.php/IBus

**Comment by w19787** [comment]
> ibus-x11 is not an x11 server, it's a program to enter special characters etc
> https://wiki.archlinux.org/index.php/IBus

thanks. is the x-session below what you mean?
![image](https://user-images.githubusercontent.com/731496/84216323-ba758a80-aafb-11ea-8bde-32a3fb9fc707.png)

**Comment by w19787** [comment]
@vfonov @gdevenyi the issue has been fixed. it is a bug of nvidia-driver 440.32. after update driver to 440.64, the register tool work fine.

thanks a lot for all your help
