### ISSUE TITLE
fast_blur illegal instruction (core dumped)

### ISSUE THREAD

**Issue by cmadjar** [BIC-MNI/minc-toolkit-v2#116]
For some reason, I cannot run fast_blur on an Ubuntu server. Our sys admins did a recent install to try to fix this but I still get the same issue.

```
$ fast_blur --fwhm 6 0.mnc 0_blur.mnc
Illegal instruction (core dumped)
```

Note: if I copy that `0.mnc` file locally on my mac, I can run `fast_blur` on it so the issue is not related to the MINC file.

I am working on a short deadline and need to deface many scans but the defacing fails because of the issue I am encountering with `fast_blur`. At least, I was able to pinpoint the issue to that...

Any advice on how to fix this would be very welcome. 

Information about the VM:
```
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by gdevenyi** [comment]
Replace fast_blur with mincblur?

How was minc-toolkit installed?

**Comment by gdevenyi** [comment]
Or, replace fast_blur with SmoothImage

**Comment by vfonov** [comment]
fast_blur (and everything else in minc-toolkit) was probably compiled for newer CPU then your server has, check the output of `cat /proc/cpuinfo |fgrep flags|head -n 1`

**Comment by cmadjar** [comment]
@vfonov here is the output of the command:

```
[lorisadmin@preventad-open-update not-backed-up]$ cat /proc/cpuinfo |fgrep flags|head -n 1
flags		: fpu de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pse36 clflush mmx fxsr sse sse2 syscall nx lm rep_good nopl tsc_known_freq pni cx16 hypervisor lahf_lm kaiser
```

seems mysterious to me...

What is strange is that I was able to run that in the past but not anymore. 

`mincblur` appears to be working though. Do you think that would have a major impact on defacing if I replace the `fast_blur` command by `mincblur`?

Thank you!

**Comment by vfonov** [comment]
looks like cpu in your VM has mmx, sse and sse2 enabled , but nothing else.  fast_blur is probably compiled to use SSE3 or AVX. 

Note that SSE2 is from the year 2000. I suspect your VMs hypervisor is actually restricting what's available to the VM. 

fast_blur and mincblur are similar if fwhm is bigger then voxel size, otherwise they are quite different.

**Comment by cmadjar** [comment]
ok. So it should be fine. Thank you! I will update the code of deface_minipe.pl on my VM then.

Thank you @gdevenyi @vfonov for your quick reply and help! :D

**Comment by cmadjar** [comment]
ooops, wrong info. `deface_minipipe.pl` calls `make_random_grid.pl` which in turns calls `fast_blur`. So `make_random_grid.pl` needs to be updated with `mincblur` instead of `fast_blur`

Just logging that into the issue in case somebody else encounters the same problem.

Feel free to close the issue.

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/minc-toolkit-v2/blob/master/cmake-modules/BuildFFTW3F.cmake#L64 - FFTW is set to use AVX/AVX2 on Linux. And everything that is linked to it , might break on that VM.

**Comment by gdevenyi** [comment]
ooo yeah, that could definitely be it. I think for the package releases we should disable that there's definitely hardware that old around.

**Comment by johnle** [comment]
Hi,

I am a sys admin working with Cecile to get this working. I am currently testing this on 4 different servers, one of which is the only one where fast_blur seems to be working after enabling 'host-passthrough' (a KVM feature) on the VM. Unfortunately, this is a dev server and we need to get it working on production.

Here is the output of `cat /proc/cpuinfo |fgrep flags|head -n 1` on dev where it is working:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single pti ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt md_clear
```

And the output of the other 3 servers where it isn't working:

Prod 1:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm ssbd ibrs ibpb stibp kaiser fsgsbase tsc_adjust smep erms xsaveopt md_clear
```

Prod 2:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb lm constant_tsc arch_perfmon nopl tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm ssbd ibrs ibpb stibp kaiser fsgsbase smep xsaveopt md_clear
```

Prod 3:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb lm constant_tsc arch_perfmon nopl tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 x2apic popcnt aes hypervisor lahf_lm ssbd ibrs ibpb stibp kaiser
```

Any additional information that you can provide to help troubleshoot this is greatly appreciated! Thanks!

**Comment by gdevenyi** [comment]
Based on this page: https://superuser.com/questions/726395/how-to-check-if-a-binary-requires-sse4-or-avx-on-linux
I grabbed this:
https://gist.github.com/SleepProgger/d4f5e0a0ea2b9456e6c7ecf256629396
and ran it against the released deb version of fast_blur

That gave me a list of CPU functions it uses:
```
Found 323 ops

pentium:
        mmx:
                psrlq
                paddusw
                psraw
                psllq
                pxor
                paddsw
                psubusw
                psrldq

x64:
        sse:
                cvtsi2ss
        mmx:
                movq
        sse2:
                cvtsi2sd
                movq

amd:
        sse4a:
                movntss

future:
        fma:
                vfmaddsub132ps
                vfmadd213ss
                vfnmadd213ss
                vfmadd213ps
                vfmsub231sd
                vfmsub213ss
                vfmadd231ss
                vfmadd231ps
                vfmsub231ps
                vfmadd132ps
                vfmsub231ss
                vfmadd132sd
                vfnmadd231ps
                vfmadd132ss
                vfnmadd132ss
                vfmadd231sd
                vfmsub132ps
                vfmsub213ps
                vfmsub132ss
                vfnmadd132ps
                vfmaddsub231ps
                vfmsubadd231ps
                vfmsubadd132ps
                vfnmadd213ps
                vfnmadd231ss
                vfmadd213sd

sandybridge:
        avx:
                vcvtss2sd
                vpmuludq
                vpsrlq
                vpcmpgtd
                vcvtsd2ss
                vmovapd
                vpxor
                vpcmpeqq
                vaddpd
                vmovdqu
                vunpcklpd
                vpaddd
                vperm2f128
                vextractf128
                vaddss
                vaddps
                vpandn
                vxorps
                vminsd
                vmulsd
                vsubps
                vsubss
                vmovhps
                vunpckhps
                vucomisd
                vpaddq
                vblendps
                vpshufd
                vmovd
                vmulps
                vmulss
                vpsubd
                vunpcklps
                vxorpd
                vaddsd
                vmovss
                vsubsd
                vcvtsi2ss
                vmovups
                vdivss
                vpor
                vpcmpgtq
                vmovshdup
                vinsertf128
                vpcmpeqd
                vmovlps
                vmovq
                vcvtsi2sd
                vmovsldup
                vcvttsd2si
                vpalignr
                vpsllq
                vmovaps
                vmovsd
                vmovdqa
                vdivsd
                vpinsrq
                vextractps
                vdivps
                vpermilps
                vbroadcastss
                vmovlhps
                vpunpcklqdq
                vptest
                vpand
                vshufps

katmai:
        sse:
                addss
                mulss
                sqrtss
                divss
                movaps
                ucomiss
                movss
                cvtps2pi
                unpckhps
                divps
                unpcklps
                movntps
                shufps
                movups
                movhps
                addps

arm:
        thumb:
                ror
                push
                adc
                or
                sub
                mul
                mov
                pop
                add
                and
                lsl
                cmp
                neg
```

I then took your dev vs production cpu feature flags, and diffed them, to get a list of "missing flags"
```
prod1: flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl [-cpuid-] tsc_known_freq pni pclmulqdq ssse3 [-fma-] cx16 pcid sse4_1 sse4_2 x2apic [-movbe-] popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm [-abm invpcid_single pti-] ssbd ibrs ibpb stibp {+kaiser+} fsgsbase tsc_adjust [-bmi1 hle avx2-] smep [-bmi2-] erms [-invpcid rtm-] xsaveopt md_clear
prod2: flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb [-rdtscp-] lm constant_tsc arch_perfmon [-rep_good-] nopl [-cpuid-] tsc_known_freq pni pclmulqdq ssse3 [-fma-] cx16 pcid sse4_1 sse4_2 x2apic [-movbe-] popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm [-abm invpcid_single pti-] ssbd ibrs ibpb stibp {+kaiser+} fsgsbase [-tsc_adjust bmi1 hle avx2-] smep [-bmi2 erms invpcid rtm-] xsaveopt md_clear
prod3: flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb [-rdtscp-] lm constant_tsc arch_perfmon [-rep_good-] nopl [-cpuid-] tsc_known_freq pni pclmulqdq ssse3 [-fma-] cx16 pcid sse4_1 sse4_2 x2apic [-movbe-] popcnt [-tsc_deadline_timer-] aes [-xsave avx f16c rdrand-] hypervisor lahf_lm [-abm invpcid_single pti-] ssbd ibrs ibpb stibp [-fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt md_clear-] {+kaiser+}
```

Taking out the flags that are missing, we have:
```
bmi2
cpuid
fma
movbe
rdtscp
rep_good
tsc_deadline_timer
```

And finally, grepping this list against the list of used features in fast_blur:
```
        fma:
                vfmaddsub132ps
                vfmadd213ss
                vfmadd213ps
                vfmadd231ss
                vfmadd231ps
                vfmadd132ps
                vfmadd132sd
                vfmadd132ss
                vfmadd231sd
                vfmaddsub231ps
                vfmadd213sd

```

Your KVM config appears to be hiding or missing the "FMA" instruction set: https://en.wikipedia.org/wiki/FMA_instruction_set

**Comment by johnle** [comment]
Thanks a lot for the quick and detailed response. Unfortunately the "FMA" instruction set is not available at the hardware level on our prod servers, so the feature cannot be passed on to the VM.

Is there a workaround for getting fast_blur to work without the FMA instruction set? i.e. Possibly compiling minc-toolkit to exclude the flag.

**Comment by gdevenyi** [comment]
Building from source on the hardware should avoid enabling the cpu flags not supported. You may also need to disable the feature cited by @vfonov above.

**Comment by johnle** [comment]
The hardware is CentOS whereas the VM is Ubuntu, which I am assuming due to the different libraries on each system would complicate things.

**Comment by gdevenyi** [comment]
Well, you should be building inside the VM.

**Comment by johnle** [comment]
I am getting this error when trying to build from source:

```
CMake Error at Testing/CMakeLists.txt:5 (file):
  file DOWNLOAD HASH mismatch

    for file: [/root/minc-toolkit-v2/build/BEAST-build/Testing/beast-testing-1.0.tar.gz]
      expected hash: [610deb21e80f72a232bbeab1267afe2b]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]



-- Configuring incomplete, errors occurred!
See also "/root/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeOutput.log".
See also "/root/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeError.log".
CMakeFiles/BEAST.dir/build.make:127: recipe for target 'BEAST-prefix/src/BEAST-stamp/BEAST-configure' failed
make[2]: *** [BEAST-prefix/src/BEAST-stamp/BEAST-configure] Error 1
CMakeFiles/Makefile2:3897: recipe for target 'CMakeFiles/BEAST.dir/all' failed
make[1]: *** [CMakeFiles/BEAST.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2
```

Thanks for your help.

**Comment by gdevenyi** [comment]
Our old link for the testing code got stale and died.

This quick patch fixes it:
https://github.com/BIC-MNI/BEaST/commit/34a526b2432408fd9a64bbf5b7b0173b74c9d83f

Or disable testing.

**Comment by johnle** [comment]
Thanks! How can I disable "FFTW" as well?

**Comment by gdevenyi** [comment]
FFTW is required by several of the underlying tools. If you build within the VM the compiler will avoid using unsupported cpu features.

**Comment by johnle** [comment]
Ah, I see. Not sure why fast_blur still isn't working then, even after building within the VM.

**Comment by gdevenyi** [comment]
Okay, I didn't expect that. Please try to delete this block https://github.com/BIC-MNI/minc-toolkit-v2/blob/master/cmake-modules/BuildFFTW3F.cmake#L56-L67 and try again.

Reminder that the alternative deployment here is to replace fast_blur with a mincblur (or SmoothImage) call in the perl script which are equivalent implementations.

**Comment by gdevenyi** [comment]
Oh and also https://github.com/BIC-MNI/minc-toolkit-v2/blob/master/cmake-modules/BuildFFTW3D.cmake#L56-L67

**Comment by gdevenyi** [comment]
I took a quick dive into the CMakeLists.txt from FFTW and I see the issue:
```
# AVX2 codelets require FMA support as well
if (ENABLE_AVX2)
  foreach (FLAG "-mfma" "/arch:FMA")
    unset (HAVE_FMA CACHE)
    check_c_compiler_flag (${FLAG} HAVE_FMA)
    if (HAVE_FMA)
      set (FMA_FLAG ${FLAG})
      break()
    endif ()
  endforeach ()
endif ()
```

While the FFWTW documentation says
> Enable various SIMD instruction sets. You need compiler that supports the given SIMD extensions, but FFTW will try to detect at runtime whether the CPU supports these extensions. That is, you can compile with--enable-avx and the code will still run on a CPU without AVX support.

That does not appear to be the case based on how the compile is configured. The compile flags seem to be set on every file allowing a compiler to use the opcode regardless.

**Comment by vfonov** [comment]
The note about being able to run on older cpu probably works when FFTW is built with autoconf/automake

**Comment by gdevenyi** [comment]
Ah indeed @vfonov, the cmake config seems undocumented on the website and is probably "new". Sadly their  last release was > 2 years ago, I suspect the project is no longer actively developed.

**Comment by vfonov** [comment]
maybe it's time to switch to something portable:
https://github.com/project-gemmi/benchmarking-fft

**Comment by gdevenyi** [comment]
:+1: for 1.9.19

**Comment by gdevenyi** [comment]
For 1.9.18 release, should we enable SSE/SSE2 and disable the AVX options?

**Comment by vfonov** [comment]
i think we should make it compatible with as many CPUs as possible, so disable both. It's not going to be a bottleneck anyway.

**Comment by gdevenyi** [comment]
SSE2 was pentium 4 in 2000, I think we can enable those :-)

**Comment by vfonov** [comment]
ok, let's keep them enabled
