### ISSUE TITLE
build fails for realease 1.9.17 but succeed on master

### ISSUE THREAD

**Issue by vincentkersten** [BIC-MNI/minc-toolkit-v2#122]
hi,
tried:   git clone --recursive --branch release-1.9.17 https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
and the build failed, on the cmake trying to find the NETCDF.
This seems to have been fixed in 'master' at the moment; when i check out
`git clone --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2`
and 
  `cmake .. -DCMAKE_BUILD_TYPE:STRING=Release   -DCMAKE_INSTALL_PREFIX:PATH=/usr/local/minc/1.9.17 -DMT_BUILD_ABC:BOOL=ON   -DMT_BUILD_ANTS:BOOL=ON   -DMT_BUILD_C3D:BOOL=ON   -DMT_BUILD_ELASTIX:BOOL=ON   -DMT_BUILD_IM:BOOL=OFF   -DMT_BUILD_ITK_TOOLS:BOOL=ON   -DMT_BUILD_LITE:BOOL=OFF   -DMT_BUILD_SHARED_LIBS:BOOL=ON   -DMT_BUILD_VISUAL_TOOLS:BOOL=ON   -DMT_USE_OPENMP:BOOL=ON   -DUSE_SYSTEM_FFTW3D:BOOL=OFF   -DUSE_SYSTEM_FFTW3F:BOOL=OFF   -DUSE_SYSTEM_GLUT:BOOL=OFF   -DUSE_SYSTEM_GSL:BOOL=OFF   -DUSE_SYSTEM_HDF5:BOOL=OFF   -DUSE_SYSTEM_ITK:BOOL=OFF   -DUSE_SYSTEM_NETCDF:BOOL=OFF   -DUSE_SYSTEM_NIFTI:BOOL=OFF   -DUSE_SYSTEM_PCRE:BOOL=OFF   -DUSE_SYSTEM_ZLIB:BOOL=OFF`
all builds well.
For other people trying to build from source, please update instructions or the release branch.

Thank you for the complete package, regards

**Comment by vfonov** [comment]
strangely, it builds fine without any changes. on Linux. Could it be transient error in accessing netcdf website? 
Can you provide exact error message?
