### ISSUE TITLE
Cannot open files on Display

### ISSUE THREAD

**Issue by SamPare** [BIC-MNI/minc-toolkit-v2#127]
Hi, I am relatively new to programming and I installed the minc-toolkit 1.9.18 and for some reasons I cannot open any files with Display. Here is the code :

Display mni_icbm152_csf_tal_nlin_sym_09c.mnc
Input mni_icbm152_csf_tal_nlin_sym_09c.mnc
/Users/vfonov/src/minc-toolkit-v2/libminc/libsrc/netcdf_convenience.c:573 (from miopen): Unable to open file 'mni_icbm152_csf_tal_nlin_sym_09c.mnc'
Error: opening MINC file "mni_icbm152_csf_tal_nlin_sym_09c.mnc".
Error loading mni_icbm152_csf_tal_nlin_sym_09c.mnc

This happens with every file I try (all are from the icbm and best library packages).
I installed the software with the package from http://bic-mni.github.io : minc-toolkit-1.9.18-20200825-Darwin-10.9-x86_64.dmg and I am on macOS Catalina.
Do you have any ideas why it does that and how I can fix it?

Thank you,
Your new fellow Samuel

**Comment by gdevenyi** [comment]
@vfonov, I believe you created the osx installers

**Comment by gdevenyi** [comment]
Can you use any other programs on the file? (`mincinfo`, or `mincstats`)

**Comment by SamPare** [comment]
Thank you for your quick response!
I have re-installed the software and it finally works! I don't know what happened, maybe there was a corrupted file but now Displays works fine.

Thank you again
