### ISSUE TITLE
Using matlab and minc-toolkit in Ubuntu

### ISSUE THREAD

**Issue by tharanic** [BIC-MNI/minc-toolkit-v2#128]
Hello,

   I was wondering if you could help me. I am a phd student at Monash university working with stroke imaging files. I would like to use matlab within Ubuntu so that I can run multiple lines of code at the same time mainly mincresample or mincmath -mult.
   It is not recognising the minc command at present within matlab. 
   Thanks 
   Tharani

**Comment by vfonov** [comment]
does `system("mincresample ....")` work?

**Comment by tharanic** [comment]
Yes but not recognised in matlab

**Comment by vfonov** [comment]
what is the output of this command?

**Comment by gdevenyi** [comment]
Probably issues with not setting up the minc environment before launching matlab.

Make sure to `source /path/to/minc/install/minc-toolkit-config.sh` in your terminal first, and launch matlab from there.
