### ISSUE TITLE
Missing header files ?

### ISSUE THREAD

**Issue by mboisson** [BIC-MNI/minc-toolkit-v2#132]
Hi,
I downloaded the latest release from Github, i.e. `minc-toolkit-v2-1.9.18.1.tar.gz` 
My `cmake` line is: 
```
cmake -DCMAKE_INSTALL_PREFIX=/home/mboisson/.local/easybuild/software/2020/avx2/Compiler/gcc9/minc-toolkit/1.9.18.1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER='gcc' -DCMAKE_C_FLAGS='-O2 -ftree-vectorize -march=core-avx2 -fno-math-errno' -DCMAKE_CXX_COMPILER='g++' -DCMAKE_CXX_FLAGS='-O2 -ftree- vectorize -march=core-avx2 -fno-math-errno' -DCMAKE_Fortran_COMPILER='gfortran' -DCMAKE_Fortran_FLAGS='-O2 -ftree-vectorize -march=core-avx2 -fno-math-errno' -DCMAKE_VERBOSE_MAKEFILE=ON  -DCMAKE_SKIP_INSTALL_RPATH=ON -DUSE_SYSTEM_FFTW3D=ON -DFFTW3D_DIR=$EBROOTFFTW -DUSE_SYSTEM_FFTW3F=ON -DUSE_SYSTEM_OPENJPEG=ON -DOPENJPEG_INCLUDE_DIR=$EBROOTGENTOO/include/      openjpeg-2.3 -DUSE_SYSTEM_GSL=ON -DUSE_SYSTEM_HDF5=ON -DUSE_SYSTEM_NETCDF=ON -DUSE_SYSTEM_PCRE=ON -DUSE_SYSTEM_ZLIB=ON -DUSE_SYSTEM_ITK=ON -DUSE_SYSTEM_JPEG=ON -DMT_BUILD_SHARED_LIBS=ON  /tmp/mboisson/avx2/MINCToolkit/1.9.18.1/GCC-9.3.0/minc-toolkit-v2/
``` 

I am getting the following errors while building: 
```
18538 /tmp/mboisson/avx2/MINCToolkit/1.9.18.1/GCC-9.3.0/minc-toolkit-v2/patch_morphology/legacy/utils.h:21:10: fatal error: minc_io_simple_volume.h: No such file or directory
18539    21 | #include <minc_io_simple_volume.h>
18540       |          ^~~~~~~~~~~~~~~~~~~~~~~~~
18541 compilation terminated.
``` 
```
18897 /tmp/mboisson/avx2/MINCToolkit/1.9.18.1/GCC-9.3.0/minc-toolkit-v2/EZminc/tools/itk_resample.cpp:70:10: fatal error: itkMINCTransformAdapter.h: No such file or directory
18898    70 | #include "itkMINCTransformAdapter.h"
18899       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~
18900 compilation terminated.
``` 

Were those files omitted from the release ?

**Comment by gdevenyi** [comment]
github does not properly package up repositories with submodules, please clone as per the instructions.

**Comment by gdevenyi** [comment]
For examples for complete starting-from-scratch build scripts, see https://github.com/BIC-MNI/build_packages where we build our packages for distribution.

https://github.com/BIC-MNI/build_packages

**Comment by vfonov** [comment]
did you download https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18.1/minc-toolkit-v2-1.9.18.1.tar.xz ?

**Comment by mboisson** [comment]
I downloaded the gzip version, 
https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18.1/minc-toolkit-v2-1.9.18.1.tar.gz

**Comment by vfonov** [comment]
did you try using system version of ITK

**Comment by mboisson** [comment]
> github does not properly package up repositories with submodules, please clone as per the instructions.

We prefer tarballs and use recursive only on last resorts, because a recursive clone which we then archive into a tarball does not yield a stable checksums, and we checksum everything to ensure repeatability. 

If there is no other choice, I will do a recurisve clone.

**Comment by mboisson** [comment]
> did you try using system version of ITK ?

yes, this is with ITK 4.13.3 as built on our clusters.

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18.1/minc-toolkit-v2-1.9.18.1.tar.gz - has all the sources

**Comment by vfonov** [comment]
> > did you try using system version of ITK ?
> 
> yes, this is with ITK 4.13.3 as built on our clusters.

Unfortunately this will not work , you have to build ITK inside minc-toolkit-v2

**Comment by mboisson** [comment]
Once I extract the tarball, 
```
[mboisson@build-node2 tmp]$ find minc-toolkit-v2/ -name 'minc_io_simple_volume.h'
minc-toolkit-v2/libminc/ezminc/minc_io_simple_volume.h
[mboisson@build-node2 tmp]$ find minc-toolkit-v2/ -name 'itkMINCTransformAdapter.h'
[mboisson@build-node2 tmp]$
``` 

so, one of them is there, but not the other one. The first one still is not found by the compiler, so there must be some missing include path.

**Comment by mboisson** [comment]
> > > did you try using system version of ITK ?
> > 
> > 
> > yes, this is with ITK 4.13.3 as built on our clusters.
> 
> Unfortunately this will not work , you have to build ITK inside minc-toolkit-v2

Mmm, why is there a `-DUSE_SYSTEM_ITK=ON '` option then ?

**Comment by vfonov** [comment]
> Once I extract the tarball,
> 
> ```
> [mboisson@build-node2 tmp]$ find minc-toolkit-v2/ -name 'minc_io_simple_volume.h'
> minc-toolkit-v2/libminc/ezminc/minc_io_simple_volume.h
> [mboisson@build-node2 tmp]$ find minc-toolkit-v2/ -name 'itkMINCTransformAdapter.h'
> [mboisson@build-node2 tmp]$
> ```
> 
> so, one of them is there, but not the other one. The first one still is not found by the compiler, so there must be some missing include path.

https://github.com/InsightSoftwareConsortium/ITK/tree/release-4.13/Modules/IO/TransformMINC/include - it is part of ITK, but depending on how you build it , you might not get it.

**Comment by vfonov** [comment]
> > > > did you try using system version of ITK ?
> > > 
> > > 
> > > yes, this is with ITK 4.13.3 as built on our clusters.
> > 
> > 
> > Unfortunately this will not work , you have to build ITK inside minc-toolkit-v2
> 
> Mmm, why is there a `-DUSE_SYSTEM_ITK=ON` option then ?

Because it is possible to build ITK with proper options to make it compatible with minc-toolkit-v2, then it is possible to use externally built ITK

**Comment by mboisson** [comment]
What are the options needed to build ITK "correctly" for MINC-Toolkit ?

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/minc-toolkit-v2/blob/release-1.9.18/cmake-modules/BuildITKv4.cmake
also you have to prebuild HDF5 , NetCDF and libminc with both of them, and then specify the same version of these libraries in minc-toolkit-v2.

Or, in short, it is complicated.

**Comment by mboisson** [comment]
Ok, I'll try without our system ITK. It still doesn't explain the other unfound header however.

**Comment by mboisson** [comment]
Rather unsurprisingly, the build of ITK as done internally fails... 
```
125273 /tmp/mboisson/avx2/MINCToolkit/1.9.18.1/GCC-9.3.0/easybuild_obj/ITKv4-build/lib/libITKFFT-4.13.so.1: error: undefined reference to 'fftwf_init_threads'
125274 /tmp/mboisson/avx2/MINCToolkit/1.9.18.1/GCC-9.3.0/easybuild_obj/ITKv4-build/lib/libITKFFT-4.13.so.1: error: undefined reference to 'fftwf_cleanup_threads'
```

**Comment by vfonov** [comment]
looks like your system-provided FFTW is built without thread support.

**Comment by mboisson** [comment]
> looks like your system-provided FFTW is built without thread support.

It is not: 
```
$ ls $EBROOTFFTW/lib
cmake            libfftw3f_omp.la        libfftw3f.so.3        libfftw3f_threads.so.3      libfftw3l_omp.a         libfftw3l.so          libfftw3l_threads.so        libfftw3_omp.so        libfftw3q_omp.a         libfftw3q.so          libfftw3q_threads.so        libfftw3.so.3.5.8      libfftw3_threads.so.3.5.8
libfftw3.a       libfftw3f_omp.so        libfftw3f.so.3.5.8    libfftw3f_threads.so.3.5.8  libfftw3l_omp.la        libfftw3l.so.3        libfftw3l_threads.so.3      libfftw3_omp.so.3      libfftw3q_omp.la        libfftw3q.so.3        libfftw3q_threads.so.3      libfftw3_threads.a     pkgconfig
libfftw3f.a      libfftw3f_omp.so.3      libfftw3f_threads.a   libfftw3.la                 libfftw3l_omp.so        libfftw3l.so.3.5.8    libfftw3l_threads.so.3.5.8  libfftw3_omp.so.3.5.8  libfftw3q_omp.so        libfftw3q.so.3.5.8    libfftw3q_threads.so.3.5.8  libfftw3_threads.la
libfftw3f.la     libfftw3f_omp.so.3.5.8  libfftw3f_threads.la  libfftw3l.a                 libfftw3l_omp.so.3      libfftw3l_threads.a   libfftw3_omp.a              libfftw3q.a            libfftw3q_omp.so.3      libfftw3q_threads.a   libfftw3.so                 libfftw3_threads.so
libfftw3f_omp.a  libfftw3f.so            libfftw3f_threads.so  libfftw3l.la                libfftw3l_omp.so.3.5.8  libfftw3l_threads.la  libfftw3_omp.la             libfftw3q.la           libfftw3q_omp.so.3.5.8  libfftw3q_threads.la  libfftw3.so.3               libfftw3_threads.so.3
```

**Comment by vfonov** [comment]
does it link to the right variation?

**Comment by mboisson** [comment]
Well, probably not, but since it is so deep in a rube goldberg machine, I have no clue how to fix it...

**Comment by vfonov** [comment]
Well... 
`conda install minc-toolkit-v2 -c vfonov`  then.

**Comment by mboisson** [comment]
conda is just as evil as superbuild and causes all types of issues on clusters. 
https://docs.computecanada.ca/wiki/Anaconda

 I guess I'll have to try to reverse engineer the ITK build to make a proper independent one. But that will have to wait.

**Comment by vfonov** [comment]
Welcome to the club
![top 10 authors](https://raw.githubusercontent.com/BIC-MNI/minc-toolkit-v2/master/analysis/minc_toolkit_v2_top10_authors.png)

**Comment by mboisson** [comment]
One thing I notice is that in the cmake line used to start the build of ITK, the threaded version of FFTW is *not* passed in parameter. Only the non-threaded version is. That is despite the `BuildITKv4.cmake`  referring to both. Only the non-threaded version ends up being passed in the command line. I will first try to patch `BuildITKv4.cmake` to use the threaded version only.

**Comment by vfonov** [comment]
```
        -DFFTWD_LIB:FILEPATH=${FFTW3_LIBRARY}
        -DFFTWD_THREADS_LIB:FILEPATH=${FFTW3_THREADS_LIBRARY}
        -DFFTWF_LIB:FILEPATH=${FFTW3F_LIBRARY}
        -DFFTWF_THREADS_LIB:FILEPATH=${FFTW3F_THREADS_LIBRARY}
        -DFFTW_INCLUDE_PATH:PATH=${FFTW3_INCLUDE_DIR}
```
https://github.com/BIC-MNI/minc-toolkit-v2/blob/develop-1.9.18/cmake-modules/BuildITKv4.cmake#L166

**Comment by mboisson** [comment]
I know, but that's not what I see in the log file right before the error.

**Comment by mboisson** [comment]
Mmm, ok, I see. It does link against the threaded version, but not the right one. 
```
[mboisson@build-node2 ~]$ ldd /tmp/mboisson/avx2/MINCToolkit/1.9.18.1/GCC-9.3.0/easybuild_obj/ITKv4-build/lib/libITKFFT-4.13.so.1 | grep threads
	libfftw3_threads.so.3 => /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/fftw/3.3.8/lib/libfftw3_threads.so.3 (0x00002b385a98a000)
[mboisson@build-node2 ~]$ nm /tmp/mboisson/avx2/MINCToolkit/1.9.18.1/GCC-9.3.0/easybuild_obj/ITKv4-build/lib/libITKFFT-4.13.so.1 | grep threads
                 U fftw_cleanup_threads
                 U fftwf_cleanup_threads
                 U fftwf_init_threads
                 U fftw_init_threads
[mboisson@build-node2 ~]$ nm /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/fftw/3.3.8/lib/libfftw3_threads.so.3 | grep init_threads
0000000000004e10 T dfftw_init_threads_
0000000000004e40 T dfftw_init_threads__
0000000000004e10 t dfftw_init_threads_.localalias
0000000000002490 T fftw_init_threads
[mboisson@build-node2 ~]$ nm /cvmfs/soft.computecanada.ca/easybuild/software/2020/avx2/Compiler/gcc9/fftw/3.3.8/lib/libfftw3f_threads.so.3 | grep init_threads
0000000000002490 T fftwf_init_threads
0000000000004e10 T sfftw_init_threads_
0000000000004e40 T sfftw_init_threads__
0000000000004e10 t sfftw_init_threads_.localalias
```

**Comment by vfonov** [comment]
just build ITK without FFTW support - it's not a big difference.

**Comment by mboisson** [comment]
At the moment, I am trying to let MINC build ITK. This is what fails. Either I modify the BuildITKv4.cmake from MINC, or there's a way to give it parameters, or I build it myself independently with corresponding parameters.

**Comment by vfonov** [comment]
you can check in `ITKv4-build` what ITK is trying to use : `cmake -LA|grep FFTW`

**Comment by mboisson** [comment]
ok, I managed to build MINC-Toolkit by patching to remove FFTW from the ITK config. 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/a13ea29fb15ed29ec9e09cd023b141aabc14b39a/easybuild/easyconfigs/m/MINC-Toolkit/MINC-Toolkit-1.9.18.1-ITK-build.patch

I'm not thrilled that all of those ITK libraries are packaged with MINC-Toolkit, but I can live with it.

**Comment by gdevenyi** [comment]
@mboisson patches are welcome to improve the build process.

**Comment by mboisson** [comment]
The patch I had to do was to disable FFTW when building ITK. I'm not sure this if is a patch you want to include or not.

**Comment by vfonov** [comment]
I find it strange that you were previously able to build 1.9.16 without these changes, https://github.com/BIC-MNI/minc-toolkit-v2/blob/release-1.9.16/cmake-modules/BuildITKv4.cmake is also linking to FFTW

**Comment by mboisson** [comment]
The last person who installed MINC let it build everything, including FFTW, which is not a good idea.

**Comment by vfonov** [comment]
I see, conda recipe works too, with fftw from conda repository.

**Comment by mboisson** [comment]
As I've stated above, Conda is also a terrible idea. We don't support Conda, it creates 2 problems for each one it solves.
