### ISSUE TITLE
Wishlist: Define CMAKE dependencies so parallel make doesn't fail

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#14]
Right now, parallel make (make -jN) fails at some points because a dependency of some other built in the CMAKE package hasn't finished. Upon restart it works fine.

It would be nice if the CMAKE modules knew the dependencies a little better so that I could run a highly parallel build and not have to restart it several times.

**Comment by gdevenyi** [comment]
Right now this is limiting my ability to do successful automated builds. I'd like to take advantage of many cpus, but the race condition causes the build to fail.

**Comment by vfonov** [comment]
make -j4 works fine on my system. So, I suggest find the missing dependency and make a pull request.

**Comment by gdevenyi** [comment]
Okay, so the race condition occours somewhere between -j4 and -j8 then since that's where I'm getting failures.

I'll see if I can find it.

**Comment by vfonov** [comment]
make sure it's not a timeout on some archive download.

**Comment by vfonov** [comment]
Just tried again:
`git clone --recursive git@github.com:BIC-MNI/minc-toolkit-v2.git`
`cmake source  -DMT_BUILD_ABC:BOOL=ON -DMT_BUILD_ANTS:BOOL=ON -DMT_BUILD_C3D:BOOL=ON -DMT_BUILD_ELASTIX:BOOL=ON -DMT_BUILD_IM:BOOL=OFF -DMT_BUILD_ITK_TOOLS:BOOL=ON -DMT_BUILD_LITE:BOOL=OFF -DMT_BUILD_QUIET:BOOL=ON -DMT_BUILD_SHARED_LIBS:BOOL=ON -DMT_BUILD_VISUAL_TOOLS:BOOL=ON -DMT_USE_OPENMP:BOOL=OFF`

`make -j16`

**Build successfull**

**Comment by gdevenyi** [comment]
Okay, this is definitely a race issue with my terrible internet here. Sometimes compiles get going faster than a download can complete.
