### ISSUE TITLE
Configure failed on AWS EC2

### ISSUE THREAD

**Issue by XinQi7788** [BIC-MNI/minc-toolkit-v2#140]
We are trying to install minc-toolkit-v2 on our AWS EC2.

The EC2 system configuration is below:
Linux ip-10-111-250-7 5.4.0-1039-aws #41~18.04.1-Ubuntu SMP Fri Feb 26 11:20:14 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

We followed the steps to configure build system to build all the tools and install them into /opt/minc/1.9.18 on the EC2  by using _ccmake .._  We set all the values as same as the configuration details on the github. 

**BUT get configuration errors as below:** Please help me on how to fix this issue. Looking forward to your reply. Thanks a lot.

CMake Deprecation Warning at mni_autoreg/CMakeLists.txt:40 (CMAKE_POLICY):
   The OLD behavior for policy CMP0026 will be removed from a future version
   of CMake.

   The cmake-policies(7) manual explains that the OLD behaviors of all
   policies are deprecated and that a policy should be set to OLD only under
   specific short-term circumstances.  Projects should be ported to the NEW
   behavior and not rely on setting a policy to OLD.

 CMake Error at cmake-modules/DownloadPackage.cmake:4 (file):
   file DOWNLOAD HASH mismatch

     for file: [/home/Xin/minc-toolkit-v2/build/cache/gsl-2.4.tar.gz]
       expected hash: [dba736f15404807834dc1c7b93e83b92]
         actual hash: [d41d8cd98f00b204e9800998ecf8427e]
              status: [22;"HTTP response code said error"]

 Call Stack (most recent call first):
   cmake-modules/BuildGSL.cmake:13 (GET_PACKAGE)
   CMakeLists.txt:437 (build_gsl)

 CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
   Could NOT find EXPAT (missing: EXPAT_LIBRARY EXPAT_INCLUDE_DIR)
 Call Stack (most recent call first):
   /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
   /usr/share/cmake-3.10/Modules/FindEXPAT.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
   CMakeLists.txt:471 (FIND_PACKAGE)

**Comment by gdevenyi** [comment]
There is no released with this fix, you can cherry pick, or patch it it yourself:
https://github.com/BIC-MNI/minc-toolkit-v2/commit/eebdf1c8ac9dca58eb2b7af49a39e8b989b63063

**Comment by gdevenyi** [comment]
However, why are you building for Ubuntu, there are binaries available at https://bic-mni.github.io/

**Comment by XinQi7788** [comment]
Hi Gabriel:

Thank you so much for the information.

Best Regards
Xin


From: Gabriel A. Devenyi ***@***.***>
Sent: Friday, August 13, 2021 2:35 PM
To: BIC-MNI/minc-toolkit-v2 ***@***.***>
Cc: Xin Qi ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [BIC-MNI/minc-toolkit-v2] Configure failed on AWS EC2 (#140)


However, why are you building for Ubuntu, there are binaries available at https://bic-mni.github.io/<https://clicktime.symantec.com/3SJwrvhwrXCcZe5gsTNZqyN7Vc?u=https%3A%2F%2Fbic-mni.github.io%2F>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://clicktime.symantec.com/3XyGMLkffVCVwtrzEH3wmSb7Vc?u=https%3A%2F%2Fgithub.com%2FBIC-MNI%2Fminc-toolkit-v2%2Fissues%2F140%23issuecomment-898648254>, or unsubscribe<https://clicktime.symantec.com/3VsVfDjvcXckAQqyEaeruQP7Vc?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FASMEXYI6WXYX5RVRJKVWNQ3T4VQUXANCNFSM5CCLYHQA>.
Triage notifications on the go with GitHub Mobile for iOS<https://clicktime.symantec.com/3E4h5ooGuGddJ6Jay6Lx5nL7Vc?u=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://clicktime.symantec.com/3GPKFPpdKhyDGVCafCW7KEn7Vc?u=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email>.


[This e-mail message may contain privileged, confidential and/or proprietary information of Eisai. If you believe that it has been sent to you in error, please contact the sender immediately and delete the message including any attachments, without copying, using, or distributing any of the information contained therein. This e-mail message should not be interpreted to include a digital or electronic signature that can be used to authenticate an agreement, contract or other legal document, nor to reflect an intention to be bound to any legally-binding agreement or contract.]
