### ISSUE TITLE
Elastix commit not available when cloning branch develop-1.9.19

### ISSUE THREAD

**Issue by antoimau** [BIC-MNI/minc-toolkit-v2#142]
Hello,

I try to build and use the latest development version of the minc-toolkit.
So I tried the following:
```
$ git clone --recursive --branch develop-1.9.19 https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
```

But this call would fail to grab and clone the Elastix submodule and displaying this error message:
```
fatal: remote error: upload-pack: not our ref a960cd3297e3d84902493a08423a2a4d034549ce
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'Elastix', but it did not contain a960cd3297e3d84902493a08423a2a4d034549ce. Direct fetching of that commit failed.
```

Also after I go inside the repository I just cloned, the folder Elastiux would be empty. When I am browsing the https://github.com/BIC-MNI/minc-toolkit-v2 page and selecting `develop-1.9.19`, if we go inside the Elastix submodule, we would get an `Error 404` web page saying the content is not available.

Did I do something wrong here? I feel the commit of Elastix associated with the branch `develop-1.9.19` is somehow bad but I could be wrong.

Thanks guys

**Comment by vfonov** [comment]
That's strange: https://github.com/vfonov/elastix/commit/a960cd3297e3d84902493a08423a2a4d034549ce

**Comment by vfonov** [comment]
not that this is early development version, Elastix doesn't even compile yet

**Comment by gdevenyi** [comment]
The submodule is pointing to a non-existent repo,

`https://github.com/vfonov/elastix-1/tree/a960cd3297e3d84902493a08423a2a4d034549ce`

**Comment by gdevenyi** [comment]
Try doing a regular clone without the branch option and then `git checkout` and `git submodule update --recursive`
