### ISSUE TITLE
Cherry-Pick Patch for ITK-4.9 development fixing masking

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#15]
Since I see you're working on ITK-4.9 update....

Just an FYI, the patchset here http://review.source.kitware.com/#/c/20443/

Fixes multiple-stage registrations with masking in antsRegistration, as documented here https://github.com/stnava/ANTs/issues/254

**Comment by vfonov** [comment]
ok, I'll make it as additional patch on top of 4.9 ITK release

**Comment by gdevenyi** [comment]
Cheers
