### ISSUE TITLE
Cmake Errors 

### ISSUE THREAD

**Issue by motazalqaoud** [BIC-MNI/minc-toolkit-v2#158]
Hello, 

I am new to the Minc toolkit, and I am trying to build it on my machine, but I wasn't successful. My machine is windows, VS 2022. I believe that I have errors with the packages that are supposed to be built internally. 

"
CMake Error at build/EZMINC-prefix/tmp/EZMINC-mkdirs.cmake:6 (file):
  file problem creating directory:
  C:/minc-toolkit-v2/build/external/C:/Program Files (x86)/minc-toolkit-v2
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.23/Modules/ExternalProject.cmake:1654 (include)
  C:/Program Files/CMake/share/cmake-3.23/Modules/ExternalProject.cmake:3592 (_ep_set_directories)
  cmake-modules/BuildEZMINC.cmake:55 (ExternalProject_Add)
  CMakeLists.txt:512 (build_EZMINC):
CMake Error at build/BEAST-prefix/tmp/BEAST-mkdirs.cmake:6 (file):
file problem creating directory:
C:/minc-toolkit-v2/build/external/C:/Program Files (x86)/minc-toolkit-v2

Call Stack (most recent call first):
C:/Program Files/CMake/share/cmake-3.23/Modules/ExternalProject.cmake:1654 (include)
C:/Program Files/CMake/share/cmake-3.23/Modules/ExternalProject.cmake:3592 (_ep_set_directories)
cmake-modules/BuildBEAST.cmake:67 (ExternalProject_Add)
CMakeLists.txt:533 (build_BEAST)
"

Looking forward to your kind feedback,

Thank you in advance,
Best regards,

Motaz

**Comment by gdevenyi** [comment]
We can't support Windows as none of us have Windows development machines.

If you want to use minc-toolkit-v2 in Windows, I suggest Ubuntu WSL.

**Comment by vfonov** [comment]
I would say that I would not support Windows even if I had Windows development machine.

**Comment by motazalqaoud** [comment]
Thank you for your kind support
