### ISSUE TITLE
Error Loading and Opening minc2 file 

### ISSUE THREAD

**Issue by motazalqaoud** [BIC-MNI/minc-toolkit-v2#159]
Hello, 

I am having an issue loading and opening my minc2 file through my program code (the error is at the end), and once it sees the file, it breaks. 

My minc file is converted from nii (Label map) by mincconvert and mnc2nii, and I can view it on mincview but not on 3D slicer or MITK, even though it can accept this format.

I have a testing minc file to make sure my code works, and it loads perfectly, and I can view it on mincview, 3D slicer, and mitk, but once I make a copy from it by using mincconvert or minccopy , the new copy does not load through my program nor 3D slicer and MITK. I checked all header data and used mincdiff to see if there was a difference, but it said it is identical. I can also save my nii file as minc2 by using 3D slicer or MITK, but it did not go through and load in my program. If I create a copy by minccopy from these new files (minc2 of 3d slicer or MITK), the copy does not load through slicer or MITK, and even it is just a literal copy.

My minc toolkit is on ubuntu 20.04, 
program: 2.4.03; libminc: 2.4.03; netcdf: 4.7.3 of Jan 23 2020 04:18:16; HDF5: 1.10.4,
My program code is compiled on windows 10, VS2010 with minc library for windows to debug on 32Win it works on two testing minc files but not the data I need to output.

I have been stuck in this loop for a while, and I do not know how I can solve it 
Do I have to create my conversion program if this seems to have a bug or if the errors are from my program if the testing files are working?

Looking forward to your kind support and thoughts  

Thank you in advance, 
Best wishes,
Motaz

Exception thrown at 0x10019364 (minc2.dll) in MultiMaterialDualContouring.exe: 0xC0000005: Access violation reading location 0xCCCCCCD4.
Unhandled exception at 0x10019364 (minc2.dll) in MultiMaterialDualContouring.exe: 0xC0000005: Access violation reading location 0xCCCCCCD4.

>	MultiMaterialDualContouring.exe!readVolumeData(std::string filename, double * segmentValues, int numSegments) Line 499	C++

**Comment by vfonov** [comment]
Check to make sure that you are creating minc2 files (that's what ITK based programs can read and write by default), in linux you can check it with file command , the output should say "Hierarchical Data Format (version 5) data"
```
> file some_file.mnc
some_file.mnc: Hierarchical Data Format (version 5) data
```

**Comment by motazalqaoud** [comment]
Thanks for the help. I checked the files, and they are in HDF5 format.  I am suspecting that since I am converting my file using the newer version of minc toolkit, NetCDF, and HDF5 etc, then using them in my program code, which is using the older version of these (probably more than 10 years old), so it causes compatibility issues to read. would that be something to consider ? or it has to be something with Dimension order (Dimorder) or LPS and RAS coordinate system?

**Comment by vfonov** [comment]
it would have been easier if you shared a sample minc file that causes the crash.

**Comment by motazalqaoud** [comment]
Sure. Please, see my data here 
https://drive.google.com/drive/folders/17KPHj7JwDfc5C36XcaXNb-gDYQVyXaBB?usp=share_link

**Comment by motazalqaoud** [comment]
Problem solved, it is an issue with my program code
