### ISSUE TITLE
Configuration failed at Cmake .. / step

### ISSUE THREAD

**Issue by reneemapa** [BIC-MNI/minc-toolkit-v2#161]
Hello,

I keep getting the same very long configuration failed error at the cmake .. / step with the posted on the install page and I cannot seem to figure out what is causing this. Any help or ideas will be very much appreciated.

[CMakeError.log](https://github.com/BIC-MNI/minc-toolkit-v2/files/10060130/CMakeError.log)

**Comment by vfonov** [comment]
These are the outputs of various checks to determine if particular function or header exists, they are expected to fail if function or header does not exists. 

Did you try installing the binary packages as described in https://bic-mni.github.io/ ?
