### ISSUE TITLE
ZLIB and GSL in release 1.9.18 and main

### ISSUE THREAD

**Issue by psteadman** [BIC-MNI/minc-toolkit-v2#162]
Hi team,

Release 1.9.18 wont build unless the zlib and gsl download paths are updated. The main branch has the gsl updated. The update zlib in main branch was just to the newer version, and actually is out of date now. It might be better to update the url instead `https://www.zlib.net/fossils/` and then whichever version of zlib you want the release to build with. Since this was 1.2.7 initially.  I dont know your policy but it might be helpful to update the release version not just the latest main branch.

I raise this as an issue because many use github to download and attempt to build minc toolkit. So it would be beneficial to the user base for the latest release to build without broken download links. 

Cheers,
Patrick

**Comment by psteadman** [comment]
I see you have updated a new release with some fixes. Perhaps consider updating the README.md file then. 

Consider `https://ftp.gnu.org/gnu/gsl/` for GSL

**Comment by inhuszar** [comment]
As of 7 April 2023, the 1.9.18 release still didn't build on my Linux Mint 21.1 machine because of this issue.

**Comment by vfonov** [comment]
> As of 7 April 2023, the 1.9.18 release still didn't build on my Linux Mint 21.1 machine because of this issue.

try `develop-1.9.18` branch

**Comment by inhuszar** [comment]
> > As of 7 April 2023, the 1.9.18 release still didn't build on my Linux Mint 21.1 machine because of this issue.
> 
> try `develop-1.9.18` branch

Thank you very much. I can confirm that this solves the current issue. My build still fails, but for some other reason that I no longer have the time to investigate in the next few days.
