### ISSUE TITLE
mnc2nii orientation incorrect?

### ISSUE THREAD

**Issue by freblisna** [BIC-MNI/minc-toolkit-v2#164]
I'm working with a .mnc file from the POND network mouse ex vivo data and when I converted it to a nii file, I noticed that the real-world orientation is not properly assigned to the nii output file despite what I think is the correct annotations in the original mnc file. Specifically, when I looked in the mnc file header ("mincheader" command in minc toolkit V2) and scrolled to the top of the header, I found the descriptions of the axes in the original mnc (img1, yellow arrows) and these are consistent with what I expected. But when I converted the file to nii ("mnc2nii" command in minc toolkit V2) and viewed it using AFNI, I noticed that the Anterior / Posterior directions were mislabeled in the image (img2, green cross-hairs and yellow arrows) and I suspect that the LR axes are also mislabeled too. Looking at the Anterior and posterior ends, it seems like the voxel number in Y is indeed increasing from posterior (Y = 135) to anterior (Y =274), as described in the mnc data, however the AP labels are switched in the nii metadata. Have I done something wrong or mis-interpreted the minc header? Or is this a bug? I also find the same incorrect interpretation of the labels using nibabel in python (nib.aff2axcodes(img.get_sform()   qform_code is 0 while sform_code is 1).

"Image 1:"
![img1_mnc file header](https://github.com/BIC-MNI/minc-toolkit-v2/assets/62805456/e358c4f2-27ff-48d5-85bf-fbc7ce828d6f)

"Image 2:"
![img2_nii file_AFNI](https://github.com/BIC-MNI/minc-toolkit-v2/assets/62805456/891c16fc-ff5e-471b-94f0-ca8735393022)

"Image 3:"
![img 3_nii file_AFNI_voxel numbers](https://github.com/BIC-MNI/minc-toolkit-v2/assets/62805456/8f2974b6-f379-4413-9af5-d76e687a5b58)

**Comment by gdevenyi** [comment]
Which version?

**Comment by freblisna** [comment]
It's minc toolkit-v2 Version 1.9.18, Ubuntu_20.04 (2020-08-13 date is in .deb filename)

Here is also a link to the minc file that I'm using if you'd like to test for yourself: https://drive.google.com/file/d/1aXlH9RANG0imqqkEF8aNMk-Ok1hcM_3S/view?usp=sharing

**Comment by vfonov** [comment]
minc header is referring to the physical coordinates (in mm), but the file have negative step size - see xspace:step , yspace:step , so the voxels are numbered in the opposite direction. mnc2nii preserves this negative step size, perhaps AFNI viewer interprets it as image in different orientation.

**Comment by freblisna** [comment]
Oh, interesting. So the Yspace: comment where it says "Y increases from posterior to anterior" is saying the physical space (in mm) goes from posterior to anterior when Y physical space becomes more positive? But here, since the step size is negative, Y physical space goes from Anterior to Posterior? I guess the Yspace comment above is thus not describing what happens to an increase in the voxel number along the Y dimension? 

But if that's all true, then why is the Y voxel index lower in the apparent posterior end of the tissue than it is in the apparent anterior end for the nii file? (Image 3). The same voxel index pattern is true when looking at the nii file in fiji (Y axis voxel coordinate is lower for posterior than it is for anterior). Its also true when looking at the minc file too using either brainbrowser.cbrain.mcgill.ca/volume-viewer or the "Display" command in minctoolkit. In all cases, Voxel number does increase from the apparent posterior to anterior ends of the tissue, while world coordinates go from positive to negative.

**Comment by andrewsilberfeld** [comment]
If i upload the minc file to brainbrowser.cbrain.mcgill.ca/volume-viewer, then i see there too that the Y voxel number does increase from posterior to anterior, consistent with the Yspace comment indicating that the increase in Y voxel number leads to a more anterior position. In parallel, the world coordinate for Y (in mm) becomes more negative moving from posterior to anterior, consistent with the negative step size.

**Comment by zijdenbos** [comment]
The standard (albeit old) tools that will show you voxel- and world
coordinates correctly, are register and Display (pretty sure they are
included in the toolkit).

Btw if the negative steps are in your way or confusing (which they often
are), a simple way to get rid of them is to use 'mincreshape +direction'.
Note that that only applies to the two fastest-varying dimensions (see the
mincreshape man page).

**Comment by freblisna** [comment]
Here's screenshots of the same .mnc file using "Display" from minctoolkit. Top row is anterior position of tissue with Y-voxel = 275 and Y-world = -3.9. Bottom row is posterior of tissue with Y-voxel = 147 and Y-world = 6.9. So here, the voxel number increases from posterior to anterior, while real-world Y decreases, consistent with the negative step size. It seems like from this (and the AFNI pictures) that the Yspace comment is actually describing the Y-voxel direction rather than the Y-physical space. I could just ignore this it but I'm particularly interested in left-right asymmetry and I'm concerned about the accuracy of the left-right label. Alternatively, it's possible the MRI technician just mislabeled the MRI directions, but I believe all the MNC files have this set of labels.

![img4_Display_voxel and world coordinates](https://github.com/BIC-MNI/minc-toolkit-v2/assets/62805456/1bf02e28-f011-4e4d-b9ad-92ad182af6a6)

**Comment by vfonov** [comment]
MINC coordinate system is the same coordinate system as encoded in DICOM, the comment "X increases from patient Left to Right" refers to the physical coordinates. This physical coordinates are encoded as voxel coordinates using the step size and direction cosines matrix. 
Now how NIFTI and AFNI interprets these numbers is a different question. I don't know what it does.

**Comment by freblisna** [comment]
Ok, thank you very much. should i then conclude that the Y axis comment is simply an incorrect assignment of the axis directions at the time of acquisition? The minc file header says Y0 -> Y+ is increasing from posterior to anterior but the real world Y coordinates in Display (Yw in the latest pic) show that positive Y is posterior but negative Y is anterior.

**Comment by vfonov** [comment]
was the mouse (i.e the "patient" ) scanned in the same orientation as you would normally scan human subject's brain?

**Comment by freblisna** [comment]
Good question, im not sure. I'll have to ask the lab that performed the mri . I imagine the mouse was lying flat on its stomach, head toward the bore & tail away from the bore.

**Comment by zijdenbos** [comment]
﻿Note that those axes (as encoded in the DICOM) tend to be good for in-vivo human scans where the position of the subject in the scanner is known, but for ex-vivo mice all bets are off. If you need to know left from right, you will need to verify exactly how the brains/heads/animals were positioned in the scanner. — A On May 14, 2023, at 17:23, andrewsilberfeld ***@***.***> wrote:﻿
Ok, thank you very much. should i then conclude that the Y axis comment is simply an incorrect assignment of the axis directions at the time of acquisition? The minc file header says Y0 -> Y+ is increasing from posterior to anterior but the real world Y coordinates in Display (Yw in the latest pic) show that positive Y is posterior but negative Y is anterior.

**Comment by freblisna** [comment]
Thanks everyone! My takeaway is that this is highly unlikely to be a bug. I will close this and discuss with the lab which generated the scans
themselves. If anything changes, i'll re-open this. 
Thanks!

**Comment by freblisna** [comment]
I confirmed with the lab which generated the scans that indeed the brain was scanned in a different orientation from the default scanner-encoded axes. The actual orientation of the sample in the scanner explains the discrepancies and matches the expected directions. Thanks all!
