### ISSUE TITLE
Wrong hash for man pages

### ISSUE THREAD

**Issue by hassemlal** [BIC-MNI/minc-toolkit-v2#19]
Hi,
The expected hash does not match the actual hash from the archive:

     for file: [/home/hassemlal/minc-toolkit-github/minc-toolkit-v2/build/man-pages/minc-man-pages-0.0.99.tar.gz]
       expected hash: [f1bf82178d4c426123a43f4ad4ca571f]
         actual hash: [d41d8cd98f00b204e9800998ecf8427e]
              status: [1;"Unsupported protocol"]

**Comment by vfonov** [comment]
You compiled cmake without ssl , so it can't download file over HTTPS protocol , hence the message " Unsupported protocol"
