### ISSUE TITLE
minc and mincbeast libraries built

### ISSUE THREAD

**Issue by athanell** [BIC-MNI/minc-toolkit-v2#28]
Hello @vfonov ,

I have built from source the mic-toolkit-v2. I want to use the mincbeast segmentation tool that requires some libraries (ADNI and ICBM). I cannot find them though in my minc-itk4 installation folder. Were these libraries supposed to be built while running make & make install for the minc-toolkit-v2 or do I need to built them separately? 

Thank you
Antonios Konstantinos

**Comment by vfonov** [comment]
Hello,

ICBM library is here: https://github.com/BIC-MNI/bic-mni-models - it's built separately

**Comment by vfonov** [comment]
Also BEaST library is here : https://github.com/BIC-MNI/BEaST_library also built separately

**Comment by athanell** [comment]
Thank you again @vfonov
