### ISSUE TITLE
PCRE md5sum is incorrect or has changed

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#3]
```
-- downloading...
     src='http://sourceforge.net/projects/pcre/files/pcre/8.37/pcre-8.37.tar.bz2'
     dst='/home/m/mchakrav/gdevenyi/projects/quarantine/minc-toolkit/1.9.10/src/build2/PCRE-prefix/src/pcre-8.37.tar.bz2'
     timeout='none'
-- [download 100% complete]
-- downloading... done
-- MD5 hash of /home/m/mchakrav/gdevenyi/projects/quarantine/minc-toolkit/1.9.10/src/build2/PCRE-prefix/src/pcre-8.37.tar.bz2
does not match expected value
  expected: ed91be292cb01d21bc7e526816c26981
    actual: 0103b909e19ca9c6497a7ae696c16480
Retrying download.
```

Confirmed multiple times on different computers.

**Comment by vfonov** [comment]
Check the contents of the file you are getting

for me it says:
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode, and currently requires
the use of javascript to function.  Please check back later.

**Comment by gdevenyi** [comment]
You're right, SF is broken.

Official release site for PCRE:
http://www.pcre.org/

Official FTP page:
ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.37.tar.bz2

That file has the right md5sum
