### ISSUE TITLE
External package PCRE should be updated to a newer version

### ISSUE THREAD

**Issue by fristed** [BIC-MNI/minc-toolkit-v2#32]
Version 8.37 is no longer available at the source URL, ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre

Works with version 8.39

**Comment by gdevenyi** [comment]
Fixed in devel here https://github.com/BIC-MNI/minc-toolkit-v2/commit/9ad0ff674db4e6655172826500ba55b1dff173af

**Comment by gdevenyi** [comment]
Can this be cherry-picked or otherwise merged into master for #33

**Comment by vfonov** [comment]
Are  you ready to beta-test release 1.9.14 ?

**Comment by gdevenyi** [comment]
I'm currently building against master. I'm a-ok with a bump to 1.9.14, can you tag it "1.9.14" instead of "release-"?

**Comment by vfonov** [comment]
All previous releases were named "release-1.9.*'

**Comment by gdevenyi** [comment]
packpack, the tool I'm using, tries to uses git tag names using semantic versioning http://semver.org/ to name builds. If tags are that format, no special modifications are needed, otherwise, I can write some sed magicks to convert current tags into something usable during build.

**Comment by vfonov** [comment]
so, what are we going to do with previous releases?

**Comment by gdevenyi** [comment]
I believe you could create alternatively named tags at the same hashes? I'm not sure.

I've only been thinking about these builds going forward so far.

**Comment by vfonov** [comment]
I would prefer to have consistency, especially in case somebody else already coded up urls like https://github.com/BIC-MNI/minc-toolkit-v2/archive/release-1.9.11.tar.gz

**Comment by gdevenyi** [comment]
Okay, I'll have to work on the sed magicks then. The tools already allow for overriding the version numbering.

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/minc-toolkit-v2/releases/tag/release-1.9.14 here you go

**Comment by gdevenyi** [comment]
Cheers thanks.

**Comment by gdevenyi** [comment]
Broken submodule config?
```
fatal: reference is not a tree: aac9526ebf4fafabdc3d396a554da535fc25ac1a
Unable to checkout 'aac9526ebf4fafabdc3d396a554da535fc25ac1a' in submodule path 'Register/Graphics'
Failed to recurse into submodule path 'Register'
```

**Comment by vfonov** [comment]
https://github.com/BIC-MNI/bicgl/tree/aac9526ebf4fafabdc3d396a554da535fc25ac1a

**Comment by vfonov** [comment]
something else is broken

**Comment by gdevenyi** [comment]
Okay, well recursive clone and submodule recursive update both fail

**Comment by vfonov** [comment]
git clone --recursive git@github.com:BIC-MNI/minc-toolkit-v2.git works fine for me

I updated to latestd Graphics (bicpl) and commited Register and minc-toolkit-v2 again - see if it works.

**Comment by gdevenyi** [comment]
Hrm, still no good:
```
Cloning into '/storage/minc-toolkit-v2/Register/m4'...
error: no such remote ref aac9526ebf4fafabdc3d396a554da535fc25ac1a
Fetched in submodule path 'Register/Graphics', but it did not contain aac9526ebf4fafabdc3d396a554da535fc25ac1a. Direct fetching of that commit failed.
```

**Comment by vfonov** [comment]
well, now it should be fetching 2f160894b8c921c5c40070a3c6907df5ae05b8bb instead.

**Comment by gdevenyi** [comment]
Something has gone wrong with Register's m4 submodule, if you click the link at https://github.com/BIC-MNI/Register it's a 404.

**Comment by gdevenyi** [comment]
Actually, something really crazy is going on.

github has the commits you reference in submodules, but I when I clone them locally those refs aren't there and I can't check them out.

**Comment by vfonov** [comment]
M4 module is not used, anyway

**Comment by gdevenyi** [comment]
Okay, I've figured it out.

It looks like @rdvincent did a force-push at some point which re-wrote the history on bicgl.

Currently Graphics is pointing at commit https://github.com/BIC-MNI/bicgl/commits/aac9526ebf4fafabdc3d396a554da535fc25ac1a

But when I clone and checkout rdv-new-opengl, I see that this commit has a different hash:
```
commit 1778c6b658d4fc0341f6a0847066014b805b9516
Author: Robert D. Vincent <robert.d.vincent@mcgill.ca>
Date:   Mon May 16 15:20:45 2016 -0400

    Fix some uninitialized fields.
```

This commit alternative tree is also there https://github.com/BIC-MNI/bicgl/commits/1778c6b658d4fc0341f6a0847066014b805b9516

**Comment by gdevenyi** [comment]
The commit tree on bicgl, if you navigate it manually on github also points at https://github.com/BIC-MNI/bicgl/commits/1778c6b658d4fc0341f6a0847066014b805b9516

**Comment by vfonov** [comment]
Well,  all i can say is when I run `git clone --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git` it works fine, hovewer git status shows `	modified:   Register (modified content)` and Register/Graphics is empty. 
But this is not a problem, since this directory is not needed for cmake build, and neither does m4.

**Comment by gdevenyi** [comment]
Can I ask your git version please. Thanks.

**Comment by vfonov** [comment]
git 2.7.4 ( from Ubuntu 16.04)

**Comment by gdevenyi** [comment]
Okay, so I can confirm I'm getting the same stuff, and if you say it's complete then we're fine.

I'll have to wrap the git calls in a "|| true" to catch the fail output for the clone/submodule update.

**Comment by gdevenyi** [comment]
This bug is resolved.

**Comment by fristed** [comment]
Thanks
