### ISSUE TITLE
Failed to recurse into submodule path 'Register'

### ISSUE THREAD

**Issue by jkenney9a** [BIC-MNI/minc-toolkit-v2#38]
When I run 
`git clone --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2` 
I get an error stating 'Failed to recurse into submodule path 'Register'. As far as I can tell, everything else downloads correctly.  Needless to say I get errors further on when I try to build, so thinking this could be the source of those additional errors.

I'm attempting to install on an Ubuntu 16.04 virtual machine.

**Comment by vfonov** [comment]
What are other errors?

**Comment by gdevenyi** [comment]
Brought this up before, there's a broken hash somewhere due to a force push. It doesn't impact the build.

**Comment by vfonov** [comment]
it was in Register/Graphics - it's not used to build minc-toolkit-v2 
Anyway, I fixed it now.
