### ISSUE TITLE
Installation Issues:  libjpeg-dev, broken links, and openjpeg.h

### ISSUE THREAD

**Issue by jkenney9a** [BIC-MNI/minc-toolkit-v2#39]
I have been attempting to install minc-toolkit-v2 on Ubuntu 16.04 and have come across several errors, some of which I've been able to resolve and perhaps should be updated:

1) It appears that libjpeg-dev is a dependency that should be listed as such on the installation instructions. When trying to configure with the MT_BUILD_VISUAL_TOOLS set to ON, without libjpeg-dev installed I get several errors indicating various files cannot be found and I cannot proceed with generation unless MT_BUILD_VISUAL_TOOLS is set to off.

2) There appear to be several broken links in some of the cmake files:

BuildPNG.cmake
The following link is broken: 
http://downloads.sourceforge.net/project/libpng/libpng16/1.6.21/libpng-1.6.21.tar.gz
I altered this to:
http://downloads.sourceforge.net/project/libpng/libpng16/1.6.28/libpng-1.6.28.tar.gz
and updated the URL_MD5 to: 897ccec1ebfb0922e83c2bfaa1be8748

BuildIM.cmake
The following link is broken:
http://mirrors-usa.go-parts.com/mirrors/ImageMagick/ImageMagick-6.9.3-8.tar.bz2
I altered this to:
http://mirrors-usa.go-parts.com/mirrors/ImageMagick/ImageMagick-6.9.7-9.tar.bz2
and updated the URL_MD5 to: d3cdff89b3d6ca5fcb8a173652441445

BuildZLIB.cmake
The following link is broken:
http://zlib.net/zlib-1.2.8.tar.gz
I updated this to:
http://zlib.net/zlib-1.2.11.tar.gz
and updated the URL_MD5 to: 1c9f62f0778697a09d36121ead88e08e

3) Finally, I am getting an error following the make command indicating that openjpeg.h cannot be found:
```
[ 35%] Building C object minctools/conversion/CMakeFiles/dcm2mnc.dir/dcm2mnc/dicom_read.c.o
/home/jkenney/minc-toolkit-v2/minctools/conversion/dcm2mnc/dicom_read.c:2486:22: fatal error: openjpeg.h: No such file or directory
compilation terminated.
minctools/conversion/CMakeFiles/dcm2mnc.dir/build.make:134: recipe for target 'minctools/conversion/CMakeFiles/dcm2mnc.dir/dcm2mnc/dicom_read.c.o' failed
make[2]: *** [minctools/conversion/CMakeFiles/dcm2mnc.dir/dcm2mnc/dicom_read.c.o] Error 1
CMakeFiles/Makefile2:6222: recipe for target 'minctools/conversion/CMakeFiles/dcm2mnc.dir/all' failed
make[1]: *** [minctools/conversion/CMakeFiles/dcm2mnc.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

```
I have openjpeg 2.2 installed, and I have altered the file 'FindOpenJPEG.cmake' so that the PATH_SUFFIXES is openjpeg-2.2. Indeed, when I look at the variable OPENJPEG_INCLUDE_DIR in ccmake, it points to /usr/local/include/openjpeg-2.2 which does indeed contain the openjpeg.h file, and the OPENJPEG_LIBRARY variable also points to the libopenjp2.so that is present. Any ideas as to how to resolve this issue?

**Comment by vfonov** [comment]
Try building develop branch ( git checkout develop; git submodule update) also don't enable MT_BUILD_IM - then you will not need libpng or ImageMagic

**Comment by jkenney9a** [comment]
Thanks, that worked.
