### ISSUE TITLE
H5cc doesn't seem to get built

### ISSUE THREAD

**Issue by cfhammill** [BIC-MNI/minc-toolkit-v2#45]
Not sure why, but installs of v2 don't seem to come with h5cc, which if I'm following the CMakelists correctly should be built by [BuildHDF5#L85](https://github.com/BIC-MNI/minc-toolkit-v2/blob/master/cmake-modules/BuildHDF5.cmake#L89) ->  [Hdf5/tools](https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/tools/src/CMakeLists.txt#16) -> [Misc#52](https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/tools/src/misc/CMakeLists.txt#52)

Any thoughts? If it got built it would help me solve https://github.com/Mouse-Imaging-Centre/RMINC/issues/77

**Comment by vfonov** [comment]
`tools/misc/CMakeLists.txt` inside of HDF5 distribution contains following line:
```
     40 #-----------------------------------------------------------------------------
     41 # Generate the h5cc file containing settings needed to compile programs
     42 #-----------------------------------------------------------------------------
     43 #if (NOT WIN32)
     44 #  configure_file (${HDF5_TOOLS_MISC_SOURCE_DIR}/h5cc.in ${HDF5_BINARY_DIR}/h5cc @ONLY)
     45 #endif (NOT WIN32)
```

**Comment by cfhammill** [comment]
I didn't even see the comment lines - I wonder why this is no longer built.

**Comment by vfonov** [comment]
Technically, making a patch for HDF5 source to uncomment these lines will be trivial.

**Comment by cfhammill** [comment]
Agreed, I suspect there is an easier way though, I think they moved h5cc out of tools into helpers, there may be a simple cmake flag to enable those. H5cc used to be provided by the hdf5-tools package in the debian repos, now it's hdf5-helpers. I'll do some more digging.

**Comment by gdevenyi** [comment]
https://forum.hdfgroup.org/t/compile-hdf5-compilers/3644

**Comment by gdevenyi** [comment]
Uncommenting the lines in https://github.com/BIC-MNI/minc-toolkit-v2/issues/45#issuecomment-305074099 successfully generates an h5cc file in the root of HDF5-build directory, however its not executable, and it doesn't get installed on `make install`. Not sure what else needs to be tweaked in the cmake config to make it install. Manually installing it afterwards, it does work as expected.

**Comment by gdevenyi** [comment]
Looks like this was probably fixed in: https://github.com/BIC-MNI/minc-toolkit-v2/commit/ef1d474604a5731f0d62d90a23c8862f910aad7f
