### ISSUE TITLE
Version of HDF5 out of date?

### ISSUE THREAD

**Issue by tfunck** [BIC-MNI/minc-toolkit-v2#46]
Hi, I ran into a problem when downloading hdf5. It seems like this version is no longer available / hosted:

src='https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.bz2'

Instead it seems like the current version is

https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.19.tar.bz2

**Comment by rdvincent** [comment]
Yes, I'm looking into fixing it. Are you building on master or develop?

**Comment by tfunck** [comment]
Hi Bert, 

This was on the develop branch. The md5sum has to be updated too.

**Comment by rdvincent** [comment]
ok just checked a change into develop. I left the old version (1.8.18) in place for now, so the md5sum doesn't have to change.

**Comment by gdevenyi** [comment]
Fixed
