### ISSUE TITLE
MD5 hash does not match expected value 

### ISSUE THREAD

**Issue by viviansmiles** [BIC-MNI/minc-toolkit-v2#54]
Hi there, 

Following the instructions for installation, I have come across an issue after entering the following command:
`make && make install`

The following error is returned

```
-- downloading...
     src='https://github.com/Unidata/netcdf-c/archive/v4.3.3.1.tar.gz'
     dst='/home/ubuntu/minc-toolkit-v2/build/NETCDF-prefix/src/v4.3.3.1.tar.gz'
     timeout='none'
```
...
```
CMake Error at NETCDF-prefix/src/NETCDF-stamp/verify-NETCDF.cmake:27 (message):
  error: MD5 hash of

    /home/ubuntu/minc-toolkit-v2/build/NETCDF-prefix/src/v4.3.3.1.tar.gz

  does not match expected value

    expected: 5c9dad3705a3408d27f696e5b31fb88c
      actual: 41fe6758d46cccb1675693d155ee7001

```

Any help would be greatly appreciated. 

Cheers,
Vivian

**Comment by vfonov** [comment]
did you build cmake with ssl support? (i.e so that it can download things over https protocol)

**Comment by gdevenyi** [comment]
Stale issue. Please reopen if you're still having issues with updated versions.
