### ISSUE TITLE
Building dcm2mnc can fail in the presence of a "new" version of openjpeg

### ISSUE THREAD

**Issue by mcvaneede** [BIC-MNI/minc-toolkit-v2#56]
When openjpeg is found on a system when the minc-toolkit is configured, the following lines are added to minctools/conversion/dcm2mnc/dicom_read.c: 

#if OPENJPEG_FOUND
#include <openjpeg.h>
#include <dlfcn.h>

The code uses type names/variables/structures such as: opj_dinfo_t, opj_cio_t and CODEC_J2K. All those were moved from openjpeg.h to openjp3d.h when openjpeg moved from version 1.5.2 to version 2.0.0. As such, the code will not be able to compile as these can not be found in openjpeg.h. 

A way around this (but probably not the best way to deal with this), is to install openjpeg 1.5.2 and point to this install in the cmake options.

**Comment by gdevenyi** [comment]
cmake should be able to a version-based check, and then the #if can be dependent on the version installed.

**Comment by vfonov** [comment]
So, I checked. openjp3d.h is not installed when you build and compile OpenJPEG 2.3.0

**Comment by mcvaneede** [comment]
True, not by default. And by default the header files that are produced do not contain opj_dinfo_t etc. You need to set the following variable during the build:

BUILD_JP3D          ON

That will add the openjp3d.h file to the produced header files. Perhaps there is another way to produce the regular header file (openjpeg.h) with these structs in it, but I did not find it...

**Comment by bcdarwin** [comment]
Hi Vlad,

Any chance of updating the version of minc-tools that comes with develop-1.9.17 to include the commit above (https://github.com/BIC-MNI/minc-tools/commit/bcc03a352f10cee18af26a8208c82a494202bcc8)?

Thanks!

**Comment by vfonov** [comment]
I think it already does

**Comment by bcdarwin** [comment]
Ah, how odd ... sorry to bother you

**Comment by vfonov** [comment]
maybe time to run git submodule update ?
