### ISSUE TITLE
Linking error with ITK-enabled tools

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#6]
This is compiling on the Debian 6.x system previously installed by Sylvain.

```
[  4%] Performing build step for 'ABC'
Linking CXX executable ABC_MINC
/opt/quarantine/minc-toolkit/1.9.10/src/build/ITKv4-build/lib/libITKIOSiemens-4.8.so.1: undefined reference to `vtable for itk::IPLFileSortInfo'
collect2: ld returned 1 exit status
make[5]: *** [StandAloneCLI/ABC_MINC] Error 1
make[4]: *** [StandAloneCLI/CMakeFiles/ABC_MINC.dir/all] Error 2
make[3]: *** [all] Error 2
make[2]: *** [ABC-prefix/src/ABC-stamp/ABC-build] Error 2
make[1]: *** [CMakeFiles/ABC.dir/all] Error 2
make: *** [all] Error 2
```

This error comes up after making the same changes described here https://github.com/BIC-MNI/minc-toolkit/issues/18 to fix the ITK linking problem.

**Comment by vfonov** [comment]
for Debian 6 and Ubuntu 10.04 you have to use -mcmodel=large for CMAKE_C_FLAGS, CMAKE_CXX_FLAGS , CMAKE_EXE_LINKER_FLAGS, CMAKE_MODULE_LINKER_FLAGS , CMAKE_SHARED_LINKER_FLAGS

**Comment by gdevenyi** [comment]
cheers!

**Comment by gdevenyi** [comment]
Hey @vfonov adding -mcmodel=large to those variables didn't fix that for me. Any other thoughts?

**Comment by vfonov** [comment]
did you rebuild everything from the scratch?

**Comment by gdevenyi** [comment]
Yes, I just removed everything, reconfigured and built again, all the ITK tools fail to link with the above error.

**Comment by vfonov** [comment]
strange - it compiles for me...
you can try adding -fkeep-inline-functions and rebuilding everything again.

**Comment by vfonov** [comment]
are you using develop or master branch?

**Comment by gdevenyi** [comment]
master... building again with inline

**Comment by vfonov** [comment]
try develop

**Comment by gdevenyi** [comment]
-DCMAKE_CXX_FLAGS:STRING=-fkeep-inline-functions on ITKv4-build and -mcmodel=large on the develop branch fixed it. Thanks @vfonov !
