### ISSUE TITLE
input_wavefront_graphics_file causes a segfault on empty files

### ISSUE THREAD

**Issue by bbbxyz** [BIC-MNI/minc-toolkit-v2#61]
using any executable calling input_wavefront_graphics_file on an empty .obj file (ex: `touch empty.obj; ray_trace empty.obj`) causes a segfault.

I suspect it is because input_wavefront_surface_file returns TRUE but sets fp to NULL on empty files

**Comment by bbbxyz** [comment]
It shouldn't be too hard to modify [input_wavefront_graphics_file](https://github.com/BIC-MNI/bicpl/blob/282bd5a373c814a41abb2c1383449035be842871/Objects/wavefront_io.c#L188) to check if the file pointer is eof. I'm wondering if it should return VIO_END_OF_FILE or VIO_ERROR in that case.

**Comment by vfonov** [comment]
VIO_END_OF_FILE i think
