### ISSUE TITLE
BEAsT not found when building version 1.9.16

### ISSUE THREAD

**Issue by mboisson** [BIC-MNI/minc-toolkit-v2#62]
Hi,
I am trying to build version 1.9.16 and cmake results in this error : 

```
-- [download 100% complete]
CMake Error at /cvmfs/soft.computecanada.ca/nix/store/pvb2n3an22sm5mi5gvz8s81ijyd7j675-cmake-cursesUI-qt4UI-3.8.2/share/cmake-3.8/Modules/ExternalProject.cmake:2005 (message):
  No download info given for 'BEAST' and its source directory:

   /home/mboisson/tmp/minc-toolkit-v2-release-1.9.16/BEaST

  is not an existing non-empty directory.  Please specify one of:
``` 

Any idea ?

**Comment by mboisson** [comment]
Note that I downloaded https://github.com/BIC-MNI/minc-toolkit-v2/archive/release-1.9.16.tar.gz  from the release page.

**Comment by vfonov** [comment]
the release archive doesn't contain subprojects, download http://packages.bic.mni.mcgill.ca/minc-toolkit/minc-toolkit-v2-1.9.16.tar.bz2 or run git clone --recursive
