### ISSUE TITLE
Toolkit Can't seem to find ImageMath on a Mac

### ISSUE THREAD

**Issue by danhps** [BIC-MNI/minc-toolkit-v2#64]
Hi Everyone,

I'm trying to run a script kindly written for me by Gabriel Devenyi, but the script hits a snag on my mac (but not his Linux). It can't seem to find ImageMath, even though ImageMath seems to be installed (verified by typing "ImageMath" into Terminal).

This is the script:

#!/bin/bash

set -x

set -euo pipefail

tmpdir=$(mktemp -d)

nii2mnc $1 ${tmpdir}/model.mnc

min=$(mincstats -quiet -min ${tmpdir}/model.mnc)
max=$(mincstats -quiet -max ${tmpdir}/model.mnc)
mincreshape -image_range ${min} ${max} -valid_range ${min} ${max} ${tmpdir}/model.mnc ${tmpdir}/model2.mnc
mv -f ${tmpdir}/model2.mnc $(basename $1 .nii).mnc

ImageMath 3 ${tmpdir}/mask.mnc ThresholdAtMean $(basename $1 .nii).mnc 5
ImageMath 3 ${tmpdir}/mask.mnc FillHoles ${tmpdir}/mask.mnc 2
iMath 3 ${tmpdir}/mask.mnc MC ${tmpdir}/mask.mnc 5 1 ball 1
ImageMath 3 ${tmpdir}/mask.mnc FillHoles ${tmpdir}/mask.mnc 2

marching_cubes ${tmpdir}/mask.mnc $(basename $1 .nii).obj 0.5 1.5

Display $(basename $1 .nii).mnc $(basename $1 .nii).obj -label ${tmpdir}/mask.mnc

rm -rf ${tmpdir}

And this is what happens when I try to run it: 

daniels-imac:MRI danielhoops$ bash Marta/make-surface-model.sh CtenophorusModels/CCa-model.aver.nii
+ set -euo pipefail
++ mktemp -d
+ tmpdir=/var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy
+ nii2mnc CtenophorusModels/CCa-model.aver.nii /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy/model.mnc
<nifti_image
  nifti_type = 'NIFTI-1+'
  header_filename = 'CtenophorusModels/CCa-model.aver.nii'
  image_filename = 'CtenophorusModels/CCa-model.aver.nii'
  image_offset = '352'
  ndim = '3'
  nx = '428'
  ny = '304'
  nz = '304'
  dx = '1'
  dy = '1'
  dz = '1'
  datatype = '16'
  datatype_name = 'FLOAT32'
  nvox = '39554048'
  nbyper = '4'
  byteorder = 'LSB_FIRST'
  scl_slope = '0.00197205'
  scl_inter = '62.2933'
  xyz_units = '2'
  xyz_units_name = 'mm'
  time_units = '8'
  time_units_name = 's'
  descrip = 'mnc2nii CCa-model.aver.mnc nii/CCa-model.aver.nii'
  sform_code = '1'
  sform_code_name = 'Scanner Anat'
  sto_xyz_matrix = '1 0 0 -211.25 0 1 0 -148.75 0 0 1 -148.75 0 0 0 1'
  sto_ijk matrix = '1 0 0 211.25 0 1 0 148.75 0 0 1 148.75 0 0 0 1'
  sform_i_orientation = 'Left-to-Right'
  sform_j_orientation = 'Posterior-to-Anterior'
  sform_k_orientation = 'Inferior-to-Superior'
  num_ext = '0'
/>
Using s-form transform:
  1.0000,   0.0000,   0.0000, -211.2500, 
  0.0000,   1.0000,   0.0000, -148.7500, 
  0.0000,   0.0000,   1.0000, -148.7500, 
  0.0000,   0.0000,   0.0000,   1.0000, 

name   | start      | step    | cosines
zspace |  -148.7500 |  1.0000 |  0.0000  0.0000  1.0000
yspace |  -148.7500 |  1.0000 |  0.0000  1.0000  0.0000
xspace |  -211.2500 |  1.0000 |  1.0000  0.0000  0.0000
++ mincstats -quiet -min /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy/model.mnc
+ min=-2.326700211
++ mincstats -quiet -max /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy/model.mnc
+ max=126.9113312
+ mincreshape -image_range -2.326700211 126.9113312 -valid_range -2.326700211 126.9113312 /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy/model.mnc /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy/model2.mnc
Copying chunks:................................................................................................................................................................................................................................................................................................................Done.
++ basename CtenophorusModels/CCa-model.aver.nii .nii
+ mv -f /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy/model2.mnc CCa-model.aver.mnc
++ basename CtenophorusModels/CCa-model.aver.nii .nii
+ ImageMath 3 /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.45Jxkczy/mask.mnc ThresholdAtMean CCa-model.aver.mnc 5
dyld: Library not loaded: libitkgdcmjpeg8-4.13.1.dylib
  Referenced from: /opt/minc/1.9.16/lib/libitkgdcmMSFF-4.13.1.dylib
  Reason: image not found
Marta/make-surface-model.sh: line 16:  1221 Abort trap: 6           ImageMath 3 ${tmpdir}/mask.mnc ThresholdAtMean $(basename $1 .nii).mnc 5
daniels-imac:MRI danielhoops$ 

I'd appreciate any help you can give!

Please remember I'm a total noob at these things...

Dan

**Comment by gdevenyi** [comment]
Missing important and relevant information:
OSX 10.13.6 “High Sierra”

**Comment by vfonov** [comment]
ImageMath built without RPATH

**Comment by danhps** [comment]
Thanks for the help! I installed version 1.9.17, but I got the same error:

+ ImageMath 3 /var/folders/6k/vhpj_p1d5x15ld8rczfjj9rr0000gn/T/tmp.0RIC5HG3/mask.mnc ThresholdAtMean CCa-model.aver.mnc 5
dyld: Library not loaded: libitkgdcmjpeg8-4.13.1.dylib
  Referenced from: /opt/minc/1.9.17/lib/libitkgdcmMSFF-4.13.1.dylib
  Reason: image not found
make-surface-model.sh: line 16:  1576 Abort trap: 6           ImageMath 3 ${tmpdir}/mask.mnc ThresholdAtMean $(basename $1 .nii).mnc 5
daniels-imac:Marta danielhoops$

**Comment by alfredomp** [comment]
I'm having the same issue:

```
$ antsRegistration
dyld: Library not loaded: libitkgdcmjpeg8-4.13.1.dylib
  Referenced from: /opt/minc/1.9.17/lib/libitkgdcmMSFF-4.13.1.dylib
  Reason: image not found
Abort trap: 6
```

@vfonov any ideas on how to solve this?

**Comment by vfonov** [comment]
which version of minc-toolkit and macos are you using?

**Comment by alfredomp** [comment]
I installed this one for mac: minc-toolkit-1.9.17-20180808-Darwin-10.10-x86_64.dmg

**Comment by vfonov** [comment]
can you run 
```
otool  -l /opt/minc/1.9.16/bin/antsRegistration |grep LC_RPATH -A 3
```
?

**Comment by alfredomp** [comment]
Sure, here is the output:

```
$ otool  -l /opt/minc/1.9.17/bin/antsRegistration |grep LC_RPATH -A 3
          cmd LC_RPATH
      cmdsize 40
         path /opt/minc/1.9.17/lib (offset 12)
```

**Comment by vfonov** [comment]
And if you run?
```
otool  -l /opt/minc/1.9.17/lib/libitkgdcmMSFF-4.13.1.dylib |grep LC_RPATH -A 3
```

**Comment by alfredomp** [comment]
I get this:
```
$ otool  -l /opt/minc/1.9.17/lib/libitkgdcmMSFF-4.13.1.dylib |grep LC_RPATH -A 3
          cmd LC_RPATH
          cmdsize 40
          path /opt/minc/1.9.17/lib (offset 12)
```

**Comment by vfonov** [comment]
Did you run `source  /opt/minc/1.9.17/minc-toolkit-config.sh` to initialize minc-toolkit environment ?

**Comment by vfonov** [comment]
You can try installing 1.9.18 from https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.18/minc-toolkit-1.9.18-20200825-Darwin-10.9-x86_64.dmg

**Comment by alfredomp** [comment]
Thank you @vfonov. I ended up installing ANTS from their source code. The other binaries from the minc-toolkit work properly.
