### ISSUE TITLE
1.9.17 release complete?

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#70]
The tagged release is still marked as "pre-release", but its from August, is it ready? Thanks!

**Comment by vfonov** [comment]
I was still fixing some bugs

**Comment by gdevenyi** [comment]
Anything I can do to assist with bug squashing?

**Comment by vfonov** [comment]
I was going to build packages based on https://github.com/BIC-MNI/minc-toolkit-v2/releases/download/release-1.9.17-test/minc-toolkit-v2-99d36e5857a4875ddd628e00f23f4f7d536d1758826c2da7f86c6fad9e718d3c.tar.xz - i,e running scripts from https://github.com/BIC-MNI/build_packages and see what happens

**Comment by gdevenyi** [comment]
Okay, I'll throw the docker build scripts at it.

**Comment by vfonov** [comment]
so, there is a bug in itk_convert ( https://github.com/BIC-MNI/EZminc/blob/ITK4/tools/itk_convert.cpp ) - somehow it stopped preserving DTI metadata , people are asking for it to be fixed.

**Comment by vfonov** [comment]
specifically DTI information from MINC does not correctly appear in NRRD , as expected in https://github.com/BIC-MNI/EZminc/blob/ITK4/tools/itk_convert.cpp#L187

**Comment by gdevenyi** [comment]
Okay, so as seen from the PRs, I'm poking at the builds and such.

Looking at  release-1.9.17-test tag, it looks quite old compared to develop-1.9.17

If I'm going to work on some things, can I do PRs against develop-1.9.17? If so, can you rebase it against master?

**Comment by vfonov** [comment]
yes, release-1.9.17-test was just to create prerelease page on github

**Comment by gdevenyi** [comment]
Hi @vfonov,

Do you have any example data you could share regarding the itk_convert bug, so I can do some testing?

**Comment by vfonov** [comment]
I will try to get one sharable. 
If you have access to the BIC system, try /scratch/scratch1/itk_convert/aspara_gus_20080404_161607_32dirs.mnc

**Comment by gdevenyi** [comment]
yup, that works, will investigate
