### ISSUE TITLE
Update vfonov/ANTs for develop-1.9.18

### ISSUE THREAD

**Issue by gdevenyi** [BIC-MNI/minc-toolkit-v2#74]
I ran into this https://github.com/ANTsX/ANTs/issues/732 and didn't realize that minc-toolkit-v2 is quite a bit behind compared to ANTs for the super build

The last ITKv4 tag in upstream is abc03dfbad1069d96e6cf19a25ef30b2937db9a1, after that we will need to do selective merges or otherwise address ITKv5.

**Comment by vfonov** [comment]
I would prefer not to change ANTs for 1.9.17, we can leave this for 1.9.18

**Comment by gdevenyi** [comment]
Okay, will try patching this failure

**Comment by gdevenyi** [comment]
Fixed
