### ISSUE TITLE
make[1]: *** [CMakeFiles/patch_morphology.dir/all] Error 2

### ISSUE THREAD

**Issue by ekuama** [BIC-MNI/minc-toolkit-v2#85]
After following the procedure
git clone --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
  cd minc-toolkit-v2
  mkdir build && cd build
  ccmake .. #
cmake .. \
-DCMAKE_BUILD_TYPE:STRING=Release   \
-DCMAKE_INSTALL_PREFIX:PATH=/opt/minc/1.9.15 \
-DMT_BUILD_ABC:BOOL=ON   \
-DMT_BUILD_ANTS:BOOL=ON   \
-DMT_BUILD_C3D:BOOL=ON   \
-DMT_BUILD_ELASTIX:BOOL=ON   \
-DMT_BUILD_IM:BOOL=OFF   \
-DMT_BUILD_ITK_TOOLS:BOOL=ON   \
-DMT_BUILD_LITE:BOOL=OFF   \
-DMT_BUILD_SHARED_LIBS:BOOL=ON   \
-DMT_BUILD_VISUAL_TOOLS:BOOL=ON   \
-DMT_USE_OPENMP:BOOL=ON   \
-DUSE_SYSTEM_FFTW3D:BOOL=OFF   \
-DUSE_SYSTEM_FFTW3F:BOOL=OFF   \
-DUSE_SYSTEM_GLUT:BOOL=OFF   \
-DUSE_SYSTEM_GSL:BOOL=OFF   \
-DUSE_SYSTEM_HDF5:BOOL=OFF   \
-DUSE_SYSTEM_ITK:BOOL=OFF   \
-DUSE_SYSTEM_NETCDF:BOOL=OFF   \
-DUSE_SYSTEM_NIFTI:BOOL=OFF   \
-DUSE_SYSTEM_PCRE:BOOL=OFF   \
-DUSE_SYSTEM_ZLIB:BOOL=OFF 

make && make install

This is the error that I get
src/CMakeFiles/itk_patch_grading.dir/build.make:242: recipe for target 'src/itk_patch_grading' failed
make[5]: *** [src/itk_patch_grading] Error 1
CMakeFiles/Makefile2:247: recipe for target 'src/CMakeFiles/itk_patch_grading.dir/all' failed
make[4]: *** [src/CMakeFiles/itk_patch_grading.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/patch_morphology.dir/build.make:110: recipe for target 'patch_morphology-prefix/src/patch_morphology-stamp/patch_morphology-build' failed
make[2]: *** [patch_morphology-prefix/src/patch_morphology-stamp/patch_morphology-build] Error 2
CMakeFiles/Makefile2:2670: recipe for target 'CMakeFiles/patch_morphology.dir/all' failed
make[1]: *** [CMakeFiles/patch_morphology.dir/all] Error 2
Makefile:162: recipe for target 'all' failed
make: *** [all] Error 2

I tried to restart the whole process by 
git clone --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
and
git checkout develop 
but the error I get is
fatal: not a git repository (or any of the parent directories): .git

Please what I am doing wrong?

Thank you for your help in advance

**Comment by gdevenyi** [comment]
The current release is 1.9.17:
```git clone --branch release-1.9.17 --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git```

**Comment by RDadarwal** [comment]
Dear Developers,

cmake in the throwing this error message in the latest release installation of minc-toolkit.

> LIBMINC_LIBRARIES_CONFIG=minc2;libhdf5_debug.a;libniftiio.a;libznz.a;libz.a
> 
>  CMake Deprecation Warning at minctools/CMakeLists.txt:24 (CMAKE_POLICY):
>    The OLD behavior for policy CMP0026 will be removed from a future version
>    of CMake.
> 
>    The cmake-policies(7) manual explains that the OLD behaviors of all
>    policies are deprecated and that a policy should be set to OLD only under
>    specific short-term circumstances.  Projects should be ported to the NEW
>    behavior and not rely on setting a policy to OLD.
> 
> 
> 
>  CMake Deprecation Warning at mni_autoreg/CMakeLists.txt:40 (CMAKE_POLICY):
>    The OLD behavior for policy CMP0026 will be removed from a future version
>    of CMake.
> 
>    The cmake-policies(7) manual explains that the OLD behaviors of all

I would greatly appreciate your reply. 
Thank you

**Comment by gdevenyi** [comment]
Hi @RDadarwal, first, please do not post new errors to unrelated issues.

Second, the output snip you have posted is clearly marked as a *warning* and does not contain the word *error*. This message is informational and does not impact the current state of the build.

**Comment by RDadarwal** [comment]
I am sorry.
