### ISSUE TITLE
mnc2nii can't find input file

### ISSUE THREAD

**Issue by christiantinauer** [BIC-MNI/minc-toolkit-v2#88]
Using mnc2nii on my Arch Linux machine leads to the following error:

```
[christiantinauer@chunkykong]: ...>$ mnc2nii margin_mask.mnc 
/home/christiantinauer/Downloads/yaourt-tmp-christiantinauer/aur-minc-toolkit-v2/src/minc-toolkit-v2/libminc/libsrc/netcdf_convenience.c:573 (from miopen): Unable to open file 'margin_mask.mnc'
Can't find input file 'margin_mask.mnc'
```

Any ideas on that?

**Comment by gdevenyi** [comment]
You need to provide an output name too

**Comment by christiantinauer** [comment]
The output name is optional and providing it does not solve the problem.

**Comment by gdevenyi** [comment]
Please provide full information on the version, build, and file you're attempting to read.

As of right now we are not able to do anything to help.

I use this command every day and it works fine here.

**Comment by zijdenbos** [comment]
Perhaps this is too obvious; but the only time I've ever had this error,
was if either the input file does not exist (does not live in the current
directory/has a different name) or the user running mnc2nii has no
permissions to read that file. Replacing 'mnc2nii' by 'ls' or 'mincinfo'
*does* work?

**Comment by christiantinauer** [comment]
Here are the outputs of mincinfo and ls:
```
[christiantinauer@chunkykong]: ~/Work/master-thesis/src/data_preprocessing/BEaST/library>$ mincinfo margin_mask.mnc 
/home/christiantinauer/Downloads/yaourt-tmp-christiantinauer/aur-minc-toolkit-v2/src/minc-toolkit-v2/libminc/libsrc/netcdf_convenience.c:573 (from miopen): Unable to open file 'margin_mask.mnc'
mincinfo: Error opening file "margin_mask.mnc"
[christiantinauer@chunkykong]: ~/Work/master-thesis/src/data_preprocessing/BEaST/library>$ ls margin_mask.mnc 
margin_mask.mnc
```
ls works but mincinfo does not.

Infos:
- Arch Linux
- minc-toolkit-v2 1.9.17 from [AUR](https://aur.archlinux.org/packages/minc-toolkit-v2/)
- margin_mask.mnc is from the BEaST library

**Comment by gdevenyi** [comment]
Can you please share the output of "file margin_mask.mnc"

Thanks.

**Comment by christiantinauer** [comment]
```
[christiantinauer@chunkykong]: ~/Work/master-thesis/src/data_preprocessing/BEaST/library>$ file margin_mask.mnc 
margin_mask.mnc: Hierarchical Data Format (version 5) data
```

**Comment by zijdenbos** [comment]
Do you have this with just *this* MINC file, or you cannot read any MINC
files? If the former, I would think something is wrong with the file itself
(maybe it was truncated in transfer or otherwise corrupted)? If the latter,
there's probably an issue with your MINC build.

**Comment by vfonov** [comment]
I would expect that there are some errors in building minc-toolkit with AUR, for example it is relying on the system-built netcdf 4.7 , and I never tested it with 4.7, so something probably changed there.

**Comment by christiantinauer** [comment]
Downgrade to netcdf 4.6.3 and recompilation of minc-toolkit-v2 fixed the problem. Somehow also the margin_mask.mnc seemed to be corrupted.

But it is working again. Thank you all for your help.

**Comment by gdevenyi** [comment]
Thanks for the assist @vfonov .

@christiantinauer can you develop a reproduction of this bug? Does 4.7 work with other files? What was root cause, was it the file or the version or both?

**Comment by vfonov** [comment]
my guess is that it tries to read hdf5 files, instead of failing as before. That's the behaviour that libminc was using for a while to distinguish between minc1 and minc2 files.

**Comment by christiantinauer** [comment]
@gdevenyi I will develop a reproduction of this bug. But currently my pipeline is in use. Summary of the things I had to do:
- Recreated the ADNI library (somehow some files were corrupted)
- Downgraded netcdf to 4.6.3
- Recompiled minc-toolkit-v2 with gcc 7.4.1 because gcc 8 and 9 gave me segfaults (see [BEaST issue](https://github.com/BIC-MNI/BEaST/issues/10)
