### ISSUE TITLE
cmake fails with undefined reference to `fftwf_set_planner_hooks'

### ISSUE THREAD

**Issue by Omroth** [BIC-MNI/minc-toolkit-v2#91]
Any help much appreciated.
Full error:

Scanning dependencies of target c2d
/execute/minc-toolkit-v2/build/external/usr/local/lib/libfftw3f_threads.a(threads.c.o): In function `fftwf_threads_register_planner_hooks':
threads.c:(.text+0x66c): undefined reference to `fftwf_set_planner_hooks'
collect2: error: ld returned 1 exit status
CMakeFiles/c2d.dir/build.make:276: recipe for target 'c2d' failed
make[5]: *** [c2d] Error 1
CMakeFiles/Makefile2:362: recipe for target 'CMakeFiles/c2d.dir/all' failed

**Comment by gdevenyi** [comment]
Hi,

Can you please provide full details of
- OS and build environment
- exact steps taken including how you downloaded the source for minc-toolkit-v2

**Comment by Omroth** [comment]
Hi.

I downloaded the minc toolkit with

git clone --recursive https://github.com/BIC-MNI/minc-toolkit-v2.git

And then used this dockerfile (situated in the root of the repo) to attempt build and install:

FROM python:3.6

RUN mkdir /execute

COPY . /execute/

RUN apt-get update && \
    apt-get install \
    minc-tools \
    libhdf5-serial-dev \
    libcurl4-gnutls-dev \
    cmake \
    bison flex \
    build-essential g++ bc \
    libx11-dev x11proto-core-dev \
    libxi6 libxi-dev \
    libxmu6 libxmu-dev libxmu-headers \
    libgl1-mesa-dev libglu1-mesa-dev \
    libjpeg-dev \
    --assume-yes

#WORKDIR /execute/netcdf-c

#RUN cmake . && \
#    make && \
#    make install

WORKDIR /execute/minc-toolkit-v2

RUN mkdir build && cd build && cmake ... \
    -DCMAKE_BUILD_TYPE:STRING=Release   \
    -DCMAKE_INSTALL_PREFIX:PATH=/opt/minc/1.9.15 \
    -DMT_BUILD_ABC:BOOL=ON   \
    -DMT_BUILD_ANTS:BOOL=ON   \
    -DMT_BUILD_C3D:BOOL=ON   \
    -DMT_BUILD_ELASTIX:BOOL=ON   \
    -DMT_BUILD_IM:BOOL=OFF   \
    -DMT_BUILD_ITK_TOOLS:BOOL=ON   \
    -DMT_BUILD_LITE:BOOL=OFF   \
    -DMT_BUILD_SHARED_LIBS:BOOL=ON   \
    -DMT_BUILD_VISUAL_TOOLS:BOOL=ON   \
    -DMT_USE_OPENMP:BOOL=ON   \
    -DUSE_SYSTEM_FFTW3D:BOOL=OFF   \
    -DUSE_SYSTEM_FFTW3F:BOOL=OFF   \
    -DUSE_SYSTEM_GLUT:BOOL=OFF   \
    -DUSE_SYSTEM_GSL:BOOL=OFF   \
    -DUSE_SYSTEM_HDF5:BOOL=OFF   \
    -DUSE_SYSTEM_ITK:BOOL=OFF   \
    -DUSE_SYSTEM_NETCDF:BOOL=OFF   \
    -DUSE_SYSTEM_NIFTI:BOOL=OFF   \
    -DUSE_SYSTEM_PCRE:BOOL=OFF   \
    -DUSE_SYSTEM_ZLIB:BOOL=OFF \
    && make && make install

WORKDIR /execute/minc-stuffs

RUN ./autogen.sh && make && make install

**Comment by Omroth** [comment]
It looks like changing the base image to ubuntu has fixed it.

**Comment by gdevenyi** [comment]
Hi.

The documentation indicates you need to clone the release tag: https://github.com/BIC-MNI/minc-toolkit-v2#installing-from-github-need-cmake--31

Otherwise you're getting the minc-toolkit-v2 master branch.

Please try that and report back.

**Comment by gdevenyi** [comment]
Also note we already have containers available https://bic-mni.github.io/#containers

And packages:
https://packages.bic.mni.mcgill.ca/minc-toolkit/

Which are built using a dockerized build system:
https://github.com/BIC-MNI/build_packages/

**Comment by Omroth** [comment]
Thank you Gabriel.

**Comment by Omroth** [comment]
I'm getting this error when running make install.

Install the project...
-- Install configuration: "Release"
-- Installing: /opt/minc/1.9.15/./bin
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot make directory "/opt/minc/1.9.15/./bin": No such file
  or directory

**Comment by gdevenyi** [comment]
First, did you start from scratch with the proper download?

Second, this indicates you don't have permissions to install to /opt. This is expected as a regular user on a linux system. If this is your system, use sudo, otherwise, you either need to install to a PREFIX where you have permissions or ask you administrator to install things for you.

**Comment by Omroth** [comment]
Yes, I've got the proper download now, and thanks it was a permissions issue.

**Comment by Omroth** [comment]
I'm sorry to keep bothering you - I expect hdf5 libraries to be installed in your containers, as the toolkit needs them, but they appear not to be - do you have a recommended install method for hdf5?

**Comment by gdevenyi** [comment]
minc-toolkit-v2 is a superbuild which includes libraries that libminc and associated tools are known to work with, this includes HDF5. You can find everything at /opt/minc/<version>
