### ISSUE TITLE
$ANTSPATH is unset during build

### ISSUE THREAD

**Issue by Dorky-Lever** [BIC-MNI/minc-toolkit-v2#93]
Hi everyone, 

$ANTSPATH is not set during the latest build and needs to be manually directed towards the location of the antsRegistrationSyNQuick.sh shell. 

Kind Regards, 
Kyle Drover

**Comment by gdevenyi** [comment]
Fixed at https://github.com/BIC-MNI/minc-toolkit-v2/commit/449ef1af17a33cf888ae2973101b93ae29d60b1b

Thanks @vfonov
