### ISSUE TITLE
Can minc-toolkit and minc-toolkit-v2 be installed on the same build?

### ISSUE THREAD

**Issue by Dorky-Lever** [BIC-MNI/minc-toolkit-v2#94]
Hi everyone, 

Is it possible to have minc-toolkit and minc-toolkit-v2 installed on the same build? 

I'm planning on testing an older version of Pydpiper (v1.15 - which needs minc-toolkit-v1) but need antsRegistration.sh (from minc-toolkit-v2) to do a different set of analysis. 

Kind Regards,
Kyle Drover

**Comment by gdevenyi** [comment]
Yes, install to different prefixes

**Comment by gdevenyi** [comment]
This is the default for the debs and rpms
