### ISSUE TITLE
MincLaplace ***Error in 'usr/bin/python': double free or corruption (!prev)

### ISSUE THREAD

**Issue by JA-Jones** [BIC-MNI/minc-toolkit-v2#96]
Hi, I am running MINC on a ubuntu (16.04) VM. Minc is installed (checked via mincinfo - returns Usage etc). Pyminc is also installed (locate pyminc gives location in '/lib/python2.7/dist-packages/pyminc'). Minclaplace is also installed correctly as command 'minclaplace' gives subsequent instruction for input. However, when I try to run 'minclaplace' with my template I get ' ***Error in 'usr/bin/python': double free or corruption (!prev)'. I think this may be a memory allocation problem, but I am unsure. I also have downloaded the VM from the cobralab github with MINC/PYMINC already installed. I have installed minclaplace on this also and get an error of  'malloc_consolidate(): invalid chunk size, aborted (core dumped)'. Could you please advise on the amount of memory and storage required for these processes. If possible, is there any test images online, e.g. the template from the minclaplace/laplacegrid and representative csv file that I could get to compare with my images? Thanks in advance. BW, Jolyon. (The attached file is the output from the ubuntu vm (not the pre-made MINC lubuntu setup from cobralab)). 

[minc_laplace_output.txt](https://github.com/BIC-MNI/minc-toolkit-v2/files/4072716/minc_laplace_output.txt)

**Comment by gdevenyi** [comment]
Hi,

minc_laplace and pyminc come from the MiCE, center, please open an issue here: https://github.com/Mouse-Imaging-Centre/minclaplace
