### ISSUE TITLE
error: #error "Dunno about this gcc" while installing ITKv4

### ISSUE THREAD

**Issue by prameshgautam** [BIC-MNI/minc-toolkit-v2#97]
I was following the instructions to install minc toolkit v2. However during the installation of ITKv4

**error: #error "Dunno about this gcc"**

this error is shown. I've tried with gcc 7, 8 and 9. Has anyone faced this issue? 

Thanks in advance

**Comment by gdevenyi** [comment]
Hi. Please profile full details of you acquired, configured and attempted to build minc toolkit with complete input and output logs.

**Comment by prameshgautam** [comment]
After running make & make install as written in the README, I get the following errors:
In file included from /media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_iostream.h:5,
                 from /media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_deprecated.cxx:4:
/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/ITKv4/Modules/ThirdParty/VNL/src/vxl/vcl/vcl_compiler.h:101:4: error: #error "Dunno about this gcc"
  101 | #  error "Dunno about this gcc"
      |    ^~~~~
make[5]: *** [Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/build.make:59: Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/vcl_deprecated.cxx.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:635: Modules/ThirdParty/VNL/src/vxl/vcl/CMakeFiles/itkvcl.dir/all] Error 2
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [CMakeFiles/ITKv4.dir/build.make:114: ITKv4-prefix/src/ITKv4-stamp/ITKv4-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:2447: CMakeFiles/ITKv4.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by gdevenyi** [comment]
You did not provide information as to how you acquired the source. As such we don't know which version you're building.

**Comment by gdevenyi** [comment]
Please provide all the exact commands and *full output*

**Comment by prameshgautam** [comment]
I cloned the release 1.9.17 and ran the following command as mentioned in the instructions

cmake .. \
-DCMAKE_BUILD_TYPE:STRING=Release   \
-DCMAKE_INSTALL_PREFIX:PATH=/opt/minc/1.9.17 \
-DMT_BUILD_ABC:BOOL=ON   \
-DMT_BUILD_ANTS:BOOL=ON   \
-DMT_BUILD_C3D:BOOL=ON   \
-DMT_BUILD_ELASTIX:BOOL=ON   \
-DMT_BUILD_IM:BOOL=OFF   \
-DMT_BUILD_ITK_TOOLS:BOOL=ON   \
-DMT_BUILD_LITE:BOOL=OFF   \
-DMT_BUILD_SHARED_LIBS:BOOL=ON   \
-DMT_BUILD_VISUAL_TOOLS:BOOL=ON   \
-DMT_USE_OPENMP:BOOL=ON   \
-DUSE_SYSTEM_FFTW3D:BOOL=OFF   \
-DUSE_SYSTEM_FFTW3F:BOOL=OFF   \
-DUSE_SYSTEM_GLUT:BOOL=OFF   \
-DUSE_SYSTEM_GSL:BOOL=OFF   \
-DUSE_SYSTEM_HDF5:BOOL=OFF   \
-DUSE_SYSTEM_ITK:BOOL=OFF   \
-DUSE_SYSTEM_NETCDF:BOOL=OFF   \
-DUSE_SYSTEM_NIFTI:BOOL=OFF   \
-DUSE_SYSTEM_PCRE:BOOL=OFF   \
-DUSE_SYSTEM_ZLIB:BOOL=OFF 

make && make install

cmake version: 3.13.4

**Comment by gdevenyi** [comment]
Can you please provide the details of
"I cloned the release 1.9.17"

As well as the complete output of:
```
cmake ..
-DCMAKE_BUILD_TYPE:STRING=Release
-DCMAKE_INSTALL_PREFIX:PATH=/opt/minc/1.9.17
-DMT_BUILD_ABC:BOOL=ON
-DMT_BUILD_ANTS:BOOL=ON
-DMT_BUILD_C3D:BOOL=ON
-DMT_BUILD_ELASTIX:BOOL=ON
-DMT_BUILD_IM:BOOL=OFF
-DMT_BUILD_ITK_TOOLS:BOOL=ON
-DMT_BUILD_LITE:BOOL=OFF
-DMT_BUILD_SHARED_LIBS:BOOL=ON
-DMT_BUILD_VISUAL_TOOLS:BOOL=ON
-DMT_USE_OPENMP:BOOL=ON
-DUSE_SYSTEM_FFTW3D:BOOL=OFF
-DUSE_SYSTEM_FFTW3F:BOOL=OFF
-DUSE_SYSTEM_GLUT:BOOL=OFF
-DUSE_SYSTEM_GSL:BOOL=OFF
-DUSE_SYSTEM_HDF5:BOOL=OFF
-DUSE_SYSTEM_ITK:BOOL=OFF
-DUSE_SYSTEM_NETCDF:BOOL=OFF
-DUSE_SYSTEM_NIFTI:BOOL=OFF
-DUSE_SYSTEM_PCRE:BOOL=OFF
-DUSE_SYSTEM_ZLIB:BOOL=OFF
```

**Comment by vfonov** [comment]
it would help to know the details of the system you are using - i.e version of OS , architecture.

**Comment by prameshgautam** [comment]
To clone the project:
**git clone --recursive --branch release-1.9.17 https://github.com/BIC-MNI/minc-toolkit-v2.git**

Output of cmake: I've uploaded the log that fit into my terminal. However, it should be enough since it contains the error portion
[log](https://www.dropbox.com/s/yfljupssywjbso1/minc_gcc_error_log.txt?dl=0)

System details:
Ubuntu 19.10
Intel i7 8750H

**Comment by vfonov** [comment]
So, it says : 
```
-- The C compiler identification is GNU 8.3.0
-- The CXX compiler identification is GNU 9.2.1
```

I think it is a little too new for VXL, the newest it support is GCC 8.3 for C++

**Comment by gdevenyi** [comment]
> this error is shown. I've tried with gcc 7, 8 and 9. Has anyone faced this issue?

Okay, thank you for the output, I see your problem.

You did
```
export CC=gcc-8
```

But failed to do:
```
export CXX=g++-8
```

That should resolve the complaint about compiler.

**Comment by prameshgautam** [comment]
> > this error is shown. I've tried with gcc 7, 8 and 9. Has anyone faced this issue?
> 
> Okay, thank you for the output, I see your problem.
> 
> You did
> 
> ```
> export CC=gcc-8
> ```
> 
> But failed to do:
> 
> ```
> export CXX=g++-8
> ```
> 
> You need to do both.
> 
> That should resolve the complaint about compiler.

That fixed the gcc issue. Thanks a lot :)

However there is the new issue now:

Determining if files vfork.h exist failed with the following output:
Change Dir: /media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_f5e26/fast"
make[3]: Entering directory '/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeTmp'
/usr/bin/make -f CMakeFiles/cmTC_f5e26.dir/build.make CMakeFiles/cmTC_f5e26.dir/build
make[4]: Entering directory '/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_f5e26.dir/HAVE_VFORK_H.c.o
/usr/bin/gcc-8    -o CMakeFiles/cmTC_f5e26.dir/HAVE_VFORK_H.c.o   -c /media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CheckIncludeFiles/HAVE_VFORK_H.c
/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CheckIncludeFiles/HAVE_VFORK_H.c:2:10: fatal error: vfork.h: No such file or directory
 #include <vfork.h>
          ^~~~~~~~~
compilation terminated.
make[4]: *** [CMakeFiles/cmTC_f5e26.dir/build.make:66: CMakeFiles/cmTC_f5e26.dir/HAVE_VFORK_H.c.o] Error 1
make[4]: Leaving directory '/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeTmp'
make[3]: *** [Makefile:121: cmTC_f5e26/fast] Error 2
make[3]: Leaving directory '/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeTmp'

Source:
/* */
#include <vfork.h>


int main(void){return 0;}

**Comment by gdevenyi** [comment]
This does not appear to be the output of the build but rather the contents of the BEAST-Build/CMakeFiles/CMakeError.log. I have the some error, but this as expected as this is simply a cmake test.

Please cleanup your build completely and start from scratch.

If there is an error, please provide the logs in full.

**Comment by prameshgautam** [comment]
I build it from scratch:
These are the final logs at the terminal

CMake Warning at CMakeLists.txt:182 (FIND_PACKAGE):
  By not providing "FindNETCDF.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "NETCDF", but
  CMake did not find one.

  Could not find a package configuration file provided by "NETCDF" with any
  of the following names:

    NETCDFConfig.cmake
    netcdf-config.cmake

  Add the installation prefix of "NETCDF" to CMAKE_PREFIX_PATH or set
  "NETCDF_DIR" to a directory containing one of the above files.  If "NETCDF"
  provides a separate development package or SDK, be sure it has been
  installed.


CMake Error at Testing/CMakeLists.txt:5 (file):
  file DOWNLOAD HASH mismatch

    for file: [/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/Testing/beast-testing-1.0.tar.gz]
      expected hash: [610deb21e80f72a232bbeab1267afe2b]
        actual hash: [d41d8cd98f00b204e9800998ecf8427e]
             status: [22;"HTTP response code said error"]



-- Configuring incomplete, errors occurred!
See also "/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeOutput.log".
See also "/media/pramesh/64DA7865DA783580/Pramesh/minc-toolkit-v2/build/BEAST-build/CMakeFiles/CMakeError.log".
make[2]: *** [CMakeFiles/BEAST.dir/build.make:106: BEAST-prefix/src/BEAST-stamp/BEAST-configure] Error 1
make[1]: *** [CMakeFiles/Makefile2:2301: CMakeFiles/BEAST.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

I have attached the complete log [here](https://www.dropbox.com/s/2h1e1cxfaydt0nd/minc_complete_log.txt?dl=0)

Actually for now, I want to be able to use register tool to view MR images. I'm not sure if it has been installed. Cannot find it in /usr/bin. It there some other way to do this?

Thanks

**Comment by vfonov** [comment]
register would not work without NetCDF. 
By the way, why don't you simply install the binary package from https://packages.bic.mni.mcgill.ca/minc-toolkit/ ? Package built for ubuntu 19.04 or 18.04 will probably work fine.

**Comment by prameshgautam** [comment]
Thanks

I was able to install using the instructions at http://bic-mni.github.io/

If anyone can help to fix the issue of building, please help in doing that.

**Comment by Schobs** [comment]
exactly the same issue about the file download hash mismatch. Has anyone solved it?

**Comment by vfonov** [comment]
d41d8cd98f00b204e9800998ecf8427e is a hash of an empty file - i.e download failed.
