### ISSUE TITLE
Installation from github - Permission denied (publickey)

### ISSUE THREAD

**Issue by ekuama** [BIC-MNI/minc-toolkit-v2#98]
sudo git clone --recursive --branch release-1.9.17 git@github.com:BIC-MNI/minc-toolkit-v2.git minc-toolkit-v2
Cloning into 'minc-toolkit-v2'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by gdevenyi** [comment]
Your SSH keys are not properly setup for Github, use HTTPS:
 git clone --recursive --branch release-1.9.17 https://github.com/BIC-MNI/minc-toolkit-v2.git

Second, there is absolutely no need to use sudo with git.
